#!/bin/bash

check_card() {
    local card_name="$1"
    local slug="$2"
    local base_slug=$(echo "$slug" | sed 's/_red$//' | sed 's/_yellow$//' | sed 's/_blue$//')
    
    # Try exact match first
    if grep -q "\"$slug\"" engine/card_effects/*.py 2>/dev/null; then
        echo "$card_name | $slug | IMPLEMENTED | triggers.py or card_triggers_extended.py"
        return
    fi
    
    # Try base slug (for cards that register without color)
    if grep -q "\"$base_slug\"" engine/card_effects/*.py 2>/dev/null; then
        echo "$card_name | $slug | IMPLEMENTED (base: $base_slug) | triggers.py or card_triggers_extended.py"
        return
    fi
    
    echo "$card_name | $slug | MISSING | "
}

echo "===== VICTOR GOLDMANE DECK ====="
echo "Card | Slug | Status | Location"
echo ""
echo "ARENA:"
check_card "Aurum Aegis" "aurum_aegis"
check_card "Crown of Dominion" "crown_of_dominion"
check_card "Fyendal's Spring Tunic" "fyendals_spring_tunic"
check_card "Ironfist Revelation" "ironfist_revelation"
check_card "Miller's Grindstone" "millers_grindstone"
check_card "Quickdodge Flexors" "quickdodge_flexors"

echo ""
echo "DECK:"
check_card "Boulder Drop (red)" "boulder_drop_red"
check_card "Command and Conquer (red)" "command_and_conquer_red"
check_card "Debilitate (red)" "debilitate_red"
check_card "Enlightened Strike (red)" "enlightened_strike_red"
check_card "Pummel (red)" "pummel_red"
check_card "Spinal Crush (red)" "spinal_crush_red"
check_card "Test of Iron Grip (red)" "test_of_iron_grip_red"
check_card "Test of Strength (red)" "test_of_strength_red"
check_card "Trounce (red)" "trounce_red"
check_card "Riches of Trōpal-Dhani (yellow)" "riches_of_trpaldhani_yellow"
check_card "Righteous Cleansing (yellow)" "righteous_cleansing_yellow"
check_card "The Golden Son (yellow)" "the_golden_son_yellow"
check_card "Cranial Crush (blue)" "cranial_crush_blue"
check_card "Debilitate (blue)" "debilitate_blue"
check_card "Disable (blue)" "disable_blue"
check_card "Headbutt (blue)" "headbutt_blue"
check_card "Macho Grande (blue)" "macho_grande_blue"
check_card "Right Behind You (blue)" "right_behind_you_blue"
check_card "Ripple Away (blue)" "ripple_away_blue"
check_card "Thunder Quake (blue)" "thunder_quake_blue"
check_card "Thunk (blue)" "thunk_blue"
check_card "Visit Goldmane Estate (blue)" "visit_goldmane_estate_blue"

echo ""
echo "HERO:"
check_card "Victor Goldmane" "victor_goldmane_high_and_mighty"

echo ""
echo "===== KAYO DECK ====="
echo "Card | Slug | Status | Location"
echo ""
echo "ARENA:"
check_card "Apex Bonebreaker" "apex_bonebreaker"
check_card "Fyendal's Spring Tunic" "fyendals_spring_tunic"
check_card "Savage Claw" "savage_claw"
check_card "Scabskin Leathers" "scabskin_leathers"
check_card "Scowling Flesh Bag" "scowling_flesh_bag"

echo ""
echo "DECK:"
check_card "Big Bully (red)" "big_bully_red"
check_card "Chain of Brutality (red)" "chain_of_brutality_red"
check_card "Command and Conquer (red)" "command_and_conquer_red"
check_card "Looking for a Scrap (red)" "looking_for_a_scrap_red"
check_card "Mocking Blow (red)" "mocking_blow_red"
check_card "Pummel (red)" "pummel_red"
check_card "Show of Strength (red)" "show_of_strength_red"
check_card "Sigil of Solace (red)" "sigil_of_solace_red"
check_card "Sink Below (red)" "sink_below_red"
check_card "Snarky Prick (red)" "snarky_prick_red"
check_card "Swing Big (red)" "swing_big_red"
check_card "Mocking Blow (yellow)" "mocking_blow_yellow"
check_card "Booze! (blue)" "booze_blue"
check_card "Insult to Injury (blue)" "insult_to_injury_blue"
check_card "Mocking Blow (blue)" "mocking_blow_blue"
check_card "Nimblism (blue)" "nimblism_blue"
check_card "Nimby (blue)" "nimby_blue"
check_card "Offensive Behavior (blue)" "offensive_behavior_blue"
check_card "Outside Interference (blue)" "outside_interference_blue"
check_card "Overcrowded (blue)" "overcrowded_blue"
check_card "Reckless Arithmetic (blue)" "reckless_arithmetic_blue"
check_card "Steal Victory (blue)" "steal_victory_blue"

echo ""
echo "HERO:"
check_card "Kayo" "kayo_underhanded_cheat"

echo ""
echo "===== ARAKNI DECK ====="
echo "Card | Slug | Status | Location"
echo ""
echo "ARENA:"
check_card "Blacktek Whisperers" "blacktek_whisperers"
check_card "Flick Knives" "flick_knives"
check_card "Fyendal's Spring Tunic" "fyendals_spring_tunic"
check_card "Hunter's Klaive" "hunters_klaive"
check_card "Mask of Deceit" "mask_of_deceit"

echo ""
echo "DECK:"
check_card "Art of Desire: Body (red)" "art_of_desire_body_red"
check_card "Command and Conquer (red)" "command_and_conquer_red"
check_card "Cut from the Same Cloth (red)" "cut_from_the_same_cloth_red"
check_card "Death Touch (red)" "death_touch_red"
check_card "Frailty Trap (red)" "frailty_trap_red"
check_card "Inertia Trap (red)" "inertia_trap_red"
check_card "Infiltrate (red)" "infiltrate_red"
check_card "Kiss of Death (red)" "kiss_of_death_red"
check_card "Lair of the Spider (red)" "lair_of_the_spider_red"
check_card "Leave No Witnesses (red)" "leave_no_witnesses_red"
check_card "Mark of the Black Widow (red)" "mark_of_the_black_widow_red"
check_card "Orb-Weaver Spinneret (red)" "orbweaver_spinneret_red"
check_card "Pain in the Backside (red)" "pain_in_the_backside_red"
check_card "Pick Up the Point (red)" "pick_up_the_point_red"
check_card "Savor Bloodshed (red)" "savor_bloodshed_red"
check_card "Scar Tissue (red)" "scar_tissue_red"
check_card "Sink Below (red)" "sink_below_red"
check_card "Stains of the Redback (red)" "stains_of_the_redback_red"
check_card "Tarantula Toxin (red)" "tarantula_toxin_red"
check_card "To the Point (red)" "to_the_point_red"
check_card "Up Sticks and Run (red)" "up_sticks_and_run_red"
check_card "Codex of Frailty (yellow)" "codex_of_frailty_yellow"
check_card "Codex of Inertia (yellow)" "codex_of_inertia_yellow"
check_card "Shred (yellow)" "shred_yellow"
check_card "Spreading Plague (yellow)" "spreading_plague_yellow"
check_card "Take Up the Mantle (yellow)" "take_up_the_mantle_yellow"
check_card "Night's Embrace (blue)" "nights_embrace_blue"
check_card "Schism of Chaos (blue)" "schism_of_chaos_blue"
check_card "Stains of the Redback (blue)" "stains_of_the_redback_blue"
check_card "Under the Trap-Door (blue)" "under_the_trapdoor_blue"

echo ""
echo "HERO:"
check_card "Arakni" "arakni_marionette"
