#!/bin/bash

check_card() {
    local slug="$1"
    local base_slug=$(echo "$slug" | sed 's/_red$//' | sed 's/_yellow$//' | sed 's/_blue$//')
    
    # Try exact match first
    if grep -q "\"$slug\"" engine/card_effects/*.py 2>/dev/null; then
        echo "FOUND (exact): $slug"
        return
    fi
    
    # Try base slug (for cards that register without color)
    if grep -q "\"$base_slug\"" engine/card_effects/*.py 2>/dev/null; then
        echo "FOUND (base): $slug"
        return
    fi
    
    echo "MISSING: $slug"
}

echo "=== VICTOR CARDS ==="
check_card "boulder_drop_red"
check_card "command_and_conquer_red"
check_card "debilitate_red"
check_card "enlightened_strike_red"
check_card "pummel_red"
check_card "spinal_crush_red"
check_card "test_of_iron_grip_red"
check_card "test_of_strength_red"
check_card "trounce_red"
check_card "riches_of_trpal_dhani_yellow"
check_card "righteous_cleansing_yellow"
check_card "the_golden_son_yellow"
check_card "cranial_crush_blue"
check_card "debilitate_blue"
check_card "disable_blue"
check_card "headbutt_blue"
check_card "macho_grande_blue"
check_card "right_behind_you_blue"
check_card "ripple_away_blue"
check_card "thunder_quake_blue"
check_card "thunk_blue"
check_card "visit_goldmane_estate_blue"
check_card "aurum_aegis"
check_card "crown_of_dominion"
check_card "fyendals_spring_tunic"
check_card "ironfist_revelation"
check_card "miller_s_grindstone"
check_card "quickdodge_flexors"
check_card "victor_goldmane_high_and_mighty"

echo ""
echo "=== KAYO CARDS ==="
check_card "big_bully_red"
check_card "chain_of_brutality_red"
check_card "looking_for_a_scrap_red"
check_card "mocking_blow_red"
check_card "show_of_strength_red"
check_card "sigil_of_solace_red"
check_card "sink_below_red"
check_card "snarky_prick_red"
check_card "swing_big_red"
check_card "mocking_blow_yellow"
check_card "booze_blue"
check_card "insult_to_injury_blue"
check_card "mocking_blow_blue"
check_card "nimblism_blue"
check_card "nimby_blue"
check_card "offensive_behavior_blue"
check_card "outside_interference_blue"
check_card "overcrowded_blue"
check_card "reckless_arithmetic_blue"
check_card "steal_victory_blue"
check_card "apex_bonebreaker"
check_card "savage_claw"
check_card "scabskin_leathers"
check_card "scowling_flesh_bag"
check_card "kayo_underhanded_cheat"

echo ""
echo "=== ARAKNI CARDS ==="
check_card "art_of_desire_body_red"
check_card "cut_from_the_same_cloth_red"
check_card "death_touch_red"
check_card "frailty_trap_red"
check_card "inertia_trap_red"
check_card "infiltrate_red"
check_card "kiss_of_death_red"
check_card "lair_of_the_spider_red"
check_card "leave_no_witnesses_red"
check_card "mark_of_the_black_widow_red"
check_card "orb_weaver_spinneret_red"
check_card "pain_in_the_backside_red"
check_card "pick_up_the_point_red"
check_card "savor_bloodshed_red"
check_card "scar_tissue_red"
check_card "sink_below_red"
check_card "stains_of_the_redback_red"
check_card "tarantula_toxin_red"
check_card "to_the_point_red"
check_card "up_sticks_and_run_red"
check_card "codex_of_frailty_yellow"
check_card "codex_of_inertia_yellow"
check_card "shred_yellow"
check_card "spreading_plague_yellow"
check_card "take_up_the_mantle_yellow"
check_card "night_s_embrace_blue"
check_card "schism_of_chaos_blue"
check_card "stains_of_the_redback_blue"
check_card "under_the_trap_door_blue"
check_card "blacktek_whisperers"
check_card "flick_knives"
check_card "hunter_s_klaive"
check_card "mask_of_deceit"
check_card "arakni_marionette"
