"""Auto-generated pytest tests for GEM card DSL implementations.
Generated by scripts/auto_implement_wtr.py — do not edit manually.
"""
import copy, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from engine.card import CardDB
from engine.card_effects.dsl import dispatch, get_card
from engine.card_effects.dsl.loader import load_all_cards
from tests.conftest import _make_state
load_all_cards()
DB = CardDB()
def _card(slug, owner=1):
    c = copy.deepcopy(DB.get(slug)); c.owner = c.controller = owner
    return c
def activate(state, card, player_id=1):
    from engine.actions import Action, ActionType
    from engine.play import apply_action
    p = state.players[player_id]; p.action_points = max(1, p.action_points)
    apply_action(state, Action(type=ActionType.ACTIVATE_CARD, player_id=player_id, card=card))
def attack(state, card, attacker=1):
    from engine.state import CombatState
    import engine.engine as _E
    bp = getattr(card, 'power', None) or getattr(card, 'base_power', None) or 0
    state.combat = CombatState(attacker_id=attacker, link_id=1, attack_power=bp, attack_card=card, keywords=[])
    state.combat.base_attack_power = bp
    dispatch(state, 'ON_ATTACK', card.slug, card=card, event=None)
    _E._recalculate_attack_power(state)
    return state.combat
def hit(state):
    ac = state.combat.attack_card; state.combat.hit = True
    dispatch(state, 'ON_HIT', ac.slug, card=ac, event=None)


# --- mark_the_prey_red ---
def test_mark_the_prey_red_on_hit_marks():
    # "When this hits a hero, mark them." attack() sets up a REAL combat (this card
    # attacking the opponent hero); hit() lands the hit so ON_HIT fires. Regression
    # guard for the harness bug where attack() set combat.attack_target, which made
    # ATTACK_TARGET_IS_HERO false and silently blocked the mark.
    st = _make_state(); st.card_db = DB
    card = _card("mark_the_prey_red")
    st.players[1].weapon1.add(card)
    attack(st, card)
    hit(st)
    assert st.players[2].class_counters.get("marked", 0) >= 1
