"""Auto-generated pytest tests for FSA card DSL implementations.
Generated by scripts/auto_implement_wtr.py — do not edit manually.
"""
import copy, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from engine.card import CardDB
from engine.card_effects.dsl import dispatch, get_card
from engine.card_effects.dsl.loader import load_all_cards
from tests.conftest import _make_state
load_all_cards()
DB = CardDB()
def _card(slug, owner=1):
    c = copy.deepcopy(DB.get(slug)); c.owner = c.controller = owner
    return c
def activate(state, card, player_id=1):
    from engine.actions import Action, ActionType
    from engine.play import apply_action
    p = state.players[player_id]; p.action_points = max(1, p.action_points)
    apply_action(state, Action(type=ActionType.ACTIVATE_CARD, player_id=player_id, card=card))


# --- blossom_of_spring ---
def test_blossom_of_spring_activate():
    # "Action - Destroy this: Gain {r}. Go again" — activate() runs the REAL flow,
    # so both the effect AND the "Destroy this" cost are checkable.
    st = _make_state(); st.card_db = DB
    card = _card("blossom_of_spring")
    st.players[1].chest.add(card)
    before = st.players[1].resources
    activate(st, card)
    assert st.players[1].resources == before + 1      # the effect (after the colon)
    assert card not in st.players[1].chest.cards       # the "Destroy this" cost was paid

def test_blossom_of_spring_gain_resource():
    # Test that Blossom of Spring correctly gains a resource point when activated.
    st = _make_state(); st.card_db = DB
    card = _card("blossom_of_spring")
    st.players[1].chest.add(card)
    before_resources = st.players[1].resources
    activate(st, card)
    assert st.players[1].resources == before_resources + 1  # Resource point gained
