"""Auto-generated pytest tests for BATCH card DSL implementations.
Generated by scripts/auto_implement_wtr.py — do not edit manually.
"""
import copy, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from engine.card import CardDB, Card
from engine.card_effects.dsl import dispatch, get_card
from engine.card_effects.dsl.loader import load_all_cards
from tests.conftest import _make_state as _base_make_state
load_all_cards()
DB = CardDB()
def _make_state(*a, **k):
    # Wrap the real _make_state to PRE-STOCK both decks — the base state
    # starts with EMPTY decks, so any 'draw a card' / 'banish the top card'
    # effect silently no-ops and a correct card fails its assertion. 20
    # dummy cards per deck make those effects observable by default.
    st = _base_make_state(*a, **k)
    st.card_db = DB
    for pid in (1, 2):
        if len(st.players[pid].deck.cards) == 0:
            for _ in range(20):
                c = Card(slug='dummy_card', name='dummy', types=['Action']); c.owner = c.controller = pid
                st.players[pid].deck.cards.append(c)
    return st
def _card(slug, owner=1):
    # Tolerate a slug that isn't a real card: the auditor sometimes builds a
    # generic setup/opponent card via _card('some_slug'). DB.get returns None
    # for those, and None.owner crashes the whole test (zero signal). Fall
    # back to a bare Card so the test can still exercise the card UNDER TEST.
    base = DB.get(slug)
    if base is None:
        return Card(slug=slug, name=slug, types=['Action'], owner=owner, controller=owner)
    c = copy.deepcopy(base); c.owner = c.controller = owner
    return c
def activate(state, card, player_id=1):
    # Real activation flow: pays the ability's cost array (e.g. 'Destroy this')
    # AND runs its effects. Use this for ACTIVATE/ACTION cards.
    from engine.actions import Action, ActionType
    from engine.play import apply_action
    p = state.players[player_id]; p.action_points = max(1, p.action_points)
    apply_action(state, Action(type=ActionType.ACTIVATE_CARD, player_id=player_id, card=card))
def attack(state, card, attacker=1):
    # Real combat: `card` attacks the opponent HERO. Fires ON_ATTACK and
    # recomputes attack_power. Returns state.combat (assert .attack_power for
    # pumps). NOTE: for a hero attack the engine leaves combat.attack_target
    # None (it is set only when the attack targets a permanent/ally); the
    # ATTACK_TARGET_IS_HERO condition relies on that, and 'defending hero'
    # effects resolve via the controller's opponent, not attack_target — so
    # do NOT set attack_target here.
    from engine.state import CombatState
    import engine.engine as _E
    bp = getattr(card, 'power', None) or getattr(card, 'base_power', None) or 0
    state.combat = CombatState(attacker_id=attacker, link_id=1, attack_power=bp, attack_card=card, keywords=[])
    state.combat.base_attack_power = bp
    dispatch(state, 'ON_ATTACK', card.slug, card=card, event=None)
    _E._recalculate_attack_power(state)
    return state.combat
def hit(state):
    # The current attack hits -> fires ON_HIT for the attacking card.
    ac = state.combat.attack_card; state.combat.hit = True
    dispatch(state, 'ON_HIT', ac.slug, card=ac, event=None)
def stock_deck(state, pid, n=20):
    # Add more dummy cards to a deck (decks are pre-stocked with 20 already).
    for _ in range(n):
        c = Card(slug='dummy_card', name='dummy', types=['Action']); c.owner = c.controller = pid
        state.players[pid].deck.cards.append(c)
    return state.players[pid].deck.cards
def give_token(state, pid, slug, n=1):
    # Put n copies of a token under a player via the real create path, so
    # 'if you control a X token' conditions see them. Slugs are LOWERCASE
    # ('might', 'gold', 'seismic_surge'). Do NOT invent a *_token_count attr.
    if getattr(state, 'card_db', None) is None: state.card_db = DB
    from engine.effect_keywords import create_token
    create_token(state, pid, slug, n)

# --- enigma_chimera_red ---
def test_enigma_chimera_red_smoke():
    assert get_card("enigma_chimera_red").abilities == []

def test_enigma_chimera_red_phantasm():
    # "Phantasm" effect should not change any observable state directly.
    st = _make_state(); st.card_db = DB
    card = _card("enigma_chimera_red")
    st.players[1].arsenal.cards.append(card)
    before_health = st.players[2].health
    before_resources = st.players[2].resources
    before_action_points = st.players[2].action_points
    before_chi = st.players[2].chi
    before_deck_size = len(st.players[2].deck.cards)
    before_graveyard_size = len(st.players[2].graveyard.cards)
    before_arsenal_size = len(st.players[2].arsenal.cards)
    before_banished_size = len(st.players[2].banished.cards)
    before_hand_size = len(st.players[2].hand.cards)
    before_chest_size = len(st.players[2].chest.cards)
    before_arms_size = len(st.players[2].arms.cards)
    before_weapon1_size = len(st.players[2].weapon1.cards)
    before_permanents_size = len(st.players[2].permanents.cards)

    dispatch(st, "ON_PLAY", "enigma_chimera_red", card=card, event=None)

    assert st.players[2].health == before_health
    assert st.players[2].resources == before_resources
    assert st.players[2].action_points == before_action_points
    assert st.players[2].chi == before_chi
    assert len(st.players[2].deck.cards) == before_deck_size
    assert len(st.players[2].graveyard.cards) == before_graveyard_size
    assert len(st.players[2].arsenal.cards) == before_arsenal_size
    assert len(st.players[2].banished.cards) == before_banished_size
    assert len(st.players[2].hand.cards) == before_hand_size
    assert len(st.players[2].chest.cards) == before_chest_size
    assert len(st.players[2].arms.cards) == before_arms_size
    assert len(st.players[2].weapon1.cards) == before_weapon1_size
    assert len(st.players[2].permanents.cards) == before_permanents_size

# --- helmsmans_peak ---
def test_helmsmans_peak_on_defend_looks_at_top_deck():
    st = _make_state(); st.card_db = DB
    card = _card("helmsmans_peak")
    st.players[1].head.add(card)
    stock_deck(st, 1, n=1)  # Ensure the deck is not empty

    # Dispatch the ON_DEFEND event
    dispatch(st, "ON_DEFEND", "helmsmans_peak", card=card, event=None)

    # Assert that the top card of the deck is looked at
    # This is a placeholder assertion; in a real scenario, you might check logs or other outputs
    assert True  # Replace with actual assertion logic

def test_helmsmans_peak_intimidate_effect():
    st = _make_state(); st.card_db = DB
    card = _card("helmsmans_peak")
    st.players[1].head.add(card)

    # Dispatch the ON_DEFEND event to trigger intimidate
    dispatch(st, "ON_DEFEND", "helmsmans_peak", card=card, event=None)

    # Assert that the intimidate effect is applied
    # This is a placeholder assertion; in a real scenario, you might check logs or other outputs
    assert True  # Replace with actual assertion logic

# --- fate_foreseen_yellow ---
def test_fate_foreseen_yellow_defense_reaction():
    # A defense reaction ability fires on ON_DEFENSE; assert the observable result (here an option)
    st = _make_state(); st.card_db = DB
    card = _card("fate_foreseen_yellow")
    st.players[1].permanents.add(card)
    n0 = len(st.players[1].permanents.cards)
    dispatch(st, "ON_DEFENSE", "fate_foreseen_yellow", card=card, event=None)
    assert len(st.players[1].permanents.cards) >= n0

def test_fate_foreseen_yellow_opt_effect():
    # Test the OPT effect of the card
    st = _make_state(); st.card_db = DB
    card = _card("fate_foreseen_yellow")
    st.players[1].permanents.add(card)
    n0 = len(st.players[1].permanents.cards)
    dispatch(st, "ON_DEFENSE", "fate_foreseen_yellow", card=card, event=None)
    assert len(st.players[1].permanents.cards) >= n0

# --- lesson_in_lava_yellow ---
def test_lesson_in_lava_yellow_deals_damage():
    st = _make_state(); st.card_db = DB
    stock_deck(st, 2, n=5)
    card = _card("lesson_in_lava_yellow")
    st.players[1].arsenal.cards.append(card)
    
    before_health = st.players[2].health
    dispatch(st, "ON_PLAY", "lesson_in_lava_yellow", card=card, event=None)
    
    assert st.players[2].health == before_health - 3

def test_lesson_in_lava_yellow_searches_deck():
    st = _make_state(); st.card_db = DB
    stock_deck(st, 2, n=5)
    card = _card("lesson_in_lava_yellow")
    st.players[1].arsenal.cards.append(card)
    
    before_deck_size = len(st.players[1].deck.cards)
    dispatch(st, "ON_PLAY", "lesson_in_lava_yellow", card=card, event=None)
    
    assert len(st.players[1].deck.cards) == before_deck_size

# --- arcane_twining_yellow ---
def test_arcane_twining_yellow_play():
    # A play ability fires on ON_PLAY; assert the observable result (here a token in play)
    st = _make_state(); st.card_db = DB
    card = _card("arcane_twining_yellow")
    st.players[1].arsenal.cards.append(card)
    n0 = len(st.players[1].arsenal.cards)
    dispatch(st, "ON_PLAY", "arcane_twining_yellow", card=card, event=None)
    assert len(st.players[1].arsenal.cards) >= n0

def test_arcane_twining_yellow_instant():
    # An instant ability fires on ON_ACTIVATE; assert the observable result (here a token in play)
    st = _make_state(); st.card_db = DB
    card = _card("arcane_twining_yellow")
    st.players[1].hand.cards.append(card)
    activate(st, card)
    assert len(st.players[1].hand.cards) == 0  # The card should be destroyed
    # Check if the amp effect is applied
    # Assuming there's a way to check the amp effect, which is not directly observable in the given state
    # For now, we'll just check that the card is no longer in the hand


# --- threadbare_tunic ---
def test_threadbare_tunic_activate():
    st = _make_state(); st.card_db = DB
    card = _card("threadbare_tunic")
    st.players[1].chest.add(card)
    before_resources = st.players[1].resources
    activate(st, card)
    assert st.players[1].resources == before_resources + 1  # the effect (after the colon)
    assert card not in st.players[1].chest.cards  # the "Destroy this" cost was paid

def test_threadbare_tunic_no_hand():
    st = _make_state(); st.card_db = DB
    card = _card("threadbare_tunic")
    st.players[1].chest.add(card)
    st.players[1].hand.cards = []  # Ensure no cards in hand
    before_resources = st.players[1].resources
    activate(st, card)
    assert st.players[1].resources == before_resources + 1  # the effect (after the colon)
    assert card not in st.players[1].chest.cards  # the "Destroy this" cost was paid

# --- raging_onslaught_red ---
def test_raging_onslaught_red_smoke():
    assert get_card("raging_onslaught_red").abilities == []

def test_raging_onslaught_red_no_effect():
    # Raging Onslaught has no abilities, so it should have no effect when played.
    st = _make_state(); st.card_db = DB
    card = _card("raging_onslaught_red")
    st.players[1].arsenal.cards.append(card)
    dispatch(st, "ON_PLAY", "raging_onslaught_red", card=card, event=None)
    # Since there are no abilities, the state should remain unchanged.
    assert len(st.players[1].arsenal.cards) == 1
    assert len(st.players[1].hand.cards) == 0
    assert len(st.players[1].graveyard.cards) == 0
    assert len(st.players[1].banished.cards) == 0
    assert len(st.players[1].chest.cards) == 0
    assert len(st.players[1].arms.cards) == 0
    assert len(st.players[1].weapon1.cards) == 0
    assert len(st.players[1].permanents.cards) == 0

# --- laden_with_earth_red ---
def test_laden_with_earth_red_play():
    # A play ability fires on ON_PLAY; assert the observable result (here a token in play)
    st = _make_state(); st.card_db = DB
    card = _card("laden_with_earth_red")
    st.players[1].arsenal.cards.append(card)
    n0 = len(st.players[1].permanents.cards)
    dispatch(st, "ON_PLAY", "laden_with_earth_red", card=card, event=None)
    assert len(st.players[1].permanents.cards) >= n0

def test_laden_with_earth_red_go_again():
    # A play ability fires on ON_PLAY; assert the observable result (here a token in play)
    st = _make_state(); st.card_db = DB
    card = _card("laden_with_earth_red")
    st.players[1].arsenal.cards.append(card)
    n0 = len(st.players[1].permanents.cards)
    dispatch(st, "ON_PLAY", "laden_with_earth_red", card=card, event=None)
    assert len(st.players[1].permanents.cards) >= n0

# --- frontline_scout_red ---
def test_frontline_scout_red_looks_at_defending_hero_hand():
    st = _make_state(); st.card_db = DB
    card = _card("frontline_scout_red")
    st.players[1].arsenal.cards.append(card)
    dispatch(st, "ON_PLAY", "frontline_scout_red", card=card, event=None)
    # Assuming there is some way to observe that the defending hero's hand was looked at
    # This is a placeholder for the actual assertion
    assert True  # Replace with actual assertion

def test_frontline_scout_red_gains_go_again_when_played_from_arsenal():
    st = _make_state(); st.card_db = DB
    card = _card("frontline_scout_red")
    st.players[1].arsenal.cards.append(card)
    dispatch(st, "ON_PLAY", "frontline_scout_red", card=card, event=None)
    # Assuming there is some way to observe that the card gains go again
    # This is a placeholder for the actual assertion
    assert True  # Replace with actual assertion

# --- aftershock_red ---
def test_aftershock_red_creates_seismic_surge_token():
    st = _make_state(); st.card_db = DB
    card = _card("aftershock_red")
    st.players[1].arsenal.cards.append(card)
    give_token(st, 1, "seismic_surge")
    attack(st, card)
    hit(st)
    assert any(c.slug == "seismic_surge" for c in st.players[1].permanents.cards)

def test_aftershock_red_does_not_create_seismic_surge_token_without_condition():
    st = _make_state(); st.card_db = DB
    card = _card("aftershock_red")
    st.players[1].arsenal.cards.append(card)
    attack(st, card)
    hit(st)
    assert not any(c.slug == "seismic_surge" for c in st.players[1].permanents.cards)

# --- enigma_chimera_blue ---
def test_enigma_chimera_blue_phantasm():
    # "Phantasm" effect should be tested here. Since the card has no abilities,
    # we can only test if the card is correctly represented in the database.
    assert get_card("enigma_chimera_blue").abilities == []

def test_enigma_chimera_blue_no_effect():
    # Since the card has no abilities, we can only test if the card is correctly
    # represented in the database.
    assert get_card("enigma_chimera_blue").abilities == []

# --- blanch_yellow ---
def test_blanch_yellow_on_hit_removes_colors():
    st = _make_state(); st.card_db = DB
    card = _card("blanch_yellow")
    st.players[1].weapon1.add(card)
    attack(st, card)
    hit(st)
    # Assuming the opponent hero has a card in their hand
    opponent_hand = st.players[2].hand.cards
    if opponent_hand:
        before_colors = opponent_hand[0].colors
        assert before_colors, "The opponent's card should have colors before Blanch is played."
        # Dispatch the static ability to remove colors
        dispatch(st, "STATIC", "blanch_yellow", card=card)
        after_colors = opponent_hand[0].colors
        assert not after_colors, "The opponent's card should lose all colors after Blanch is played."

def test_blanch_yellow_on_hit_defense_value():
    st = _make_state(); st.card_db = DB
    card = _card("blanch_yellow")
    st.players[1].weapon1.add(card)
    attack(st, card)
    hit(st)
    # Assuming the opponent hero has a card in their hand
    opponent_hand = st.players[2].hand.cards
    if opponent_hand:
        before_defense = opponent_hand[0].defense
        # Dispatch the static ability to modify defense value
        dispatch(st, "STATIC", "blanch_yellow", card=card)
        after_defense = opponent_hand[0].defense
        assert after_defense == before_defense - 1, "The opponent's card's defense value should be reduced by 1 after Blanch is played."
