"""Auto-generated pytest tests for WTR card DSL implementations.
Generated by scripts/auto_implement_wtr.py — do not edit manually.
"""
from __future__ import annotations
import json, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from engine.card_effects.dsl import dispatch, get_card


# --- anothos ---
def test_anothos_ability_fires_on_correct_trigger():
    card = get_card("anothos")
    pitch_zone = [{"cost": 3}, {"cost": 4}]
    state = {
        "pitch_zone": pitch_zone,
        "card": card
    }
    result = dispatch(state, "attack", {})
    assert result["attack_power"] == 2

def test_anothos_condition_gates_correctly():
    card = get_card("anothos")
    pitch_zone = [{"cost": 3}, {"cost": 2}]
    state = {
        "pitch_zone": pitch_zone,
        "card": card
    }
    result = dispatch(state, "attack", {})
    assert result["attack_power"] == 0

def test_anothos_effect_produces_expected_state_change():
    card = get_card("anothos")
    pitch_zone = [{"cost": 3}, {"cost": 4}, {"cost": 5}]
    state = {
        "pitch_zone": pitch_zone,
        "card": card
    }
    result = dispatch(state, "attack", {})
    assert result["attack_power"] == 4

# --- barkbone_strapping ---
def test_barkbone_strapping_ability_fires_on_correct_trigger():
    card = get_card("barkbone_strapping")
    state = {
        "player": {
            "resources": 0,
            "hand": [],
            "battlefield": [card]
        }
    }
    
    # Simulate the activation of Barkbone Strapping
    dispatch(state, "ACTIVATE", card)
    
    # Check if the card is no longer on the battlefield (destroyed)
    assert card not in state["player"]["battlefield"]
    
    # Check if resources were gained correctly
    expected_resources = 3  # Assuming a roll of 6 for simplicity
    assert state["player"]["resources"] == expected_resources

def test_barkbone_strapping_condition_gates_correctly():
    card = get_card("barkbone_strapping")
    state = {
        "player": {
            "resources": 0,
            "hand": [],
            "battlefield": []
        }
    }
    
    # Try to activate Barkbone Strapping without it on the battlefield
    dispatch(state, "ACTIVATE", card)
    
    # Check if resources were not gained (condition failed)
    assert state["player"]["resources"] == 0

def test_barkbone_strapping_effect_produces_expected_state_change():
    card = get_card("barkbone_strapping")
    state = {
        "player": {
            "resources": 0,
            "hand": [],
            "battlefield": [card]
        }
    }
    
    # Simulate the activation of Barkbone Strapping with a specific roll
    dispatch(state, "ACTIVATE", card, roll=4)
    
    # Check if the card is no longer on the battlefield (destroyed)
    assert card not in state["player"]["battlefield"]
    
    # Check if resources were gained correctly (half of 4 rounded down)
    expected_resources = 2
    assert state["player"]["resources"] == expected_resources

# --- barraging_brawnhide_blue ---
def test_barraging_brawnhide_blue_ability_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("barraging_brawnhide_blue")
    defender_hand = [{"type": "Non-Equipment"}, {"type": "Equipment"}]
    
    # Dispatch the effect with mock state
    result = dispatch(card, "DEFENDER_USED_HAND_CARD", hand=defender_hand)
    
    # Assert that the ability did not fire because one of the cards is equipment
    assert result == None

def test_barraging_brawnhide_blue_condition_gates_correctly():
    # Mock state setup
    card = get_card("barraging_brawnhide_blue")
    defender_hand = [{"type": "Non-Equipment"}, {"type": "Non-Equipment"}]
    
    # Dispatch the effect with mock state
    result = dispatch(card, "DEFENDER_USED_HAND_CARD", hand=defender_hand)
    
    # Assert that the ability fired because both cards are non-equipment
    assert result == 1

def test_barraging_brawnhide_blue_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("barraging_brawnhide_blue")
    defender_hand = [{"type": "Non-Equipment"}, {"type": "Non-Equipment"}]
    
    # Dispatch the effect with mock state
    result = dispatch(card, "DEFENDER_USED_HAND_CARD", hand=defender_hand)
    
    # Assert that the attack power is modified by +1
    assert result == 1

# --- barraging_brawnhide_red ---
def test_barraging_brawnhide_red_ability_fires_on_correct_trigger():
    card = get_card("barraging_brawnhide_red")
    state = {
        "defense": [
            {"type": "Creature"},
            {"type": "Equipment"}
        ]
    }
    result = dispatch(card, state)
    assert result == None  # No effect should apply because there is an Equipment in defense

def test_barraging_brawnhide_red_condition_gates_correctly():
    card = get_card("barraging_brawnhide_red")
    state = {
        "defense": [
            {"type": "Creature"}
        ]
    }
    result = dispatch(card, state)
    assert result == {"modify_attack_power": 1}  # Effect should apply because there is less than 2 non-equipment cards in defense

def test_barraging_brawnhide_red_effect_produces_expected_state_change():
    card = get_card("barraging_brawnhide_red")
    state = {
        "defense": [
            {"type": "Creature"}
        ],
        "attack_power": 5
    }
    result = dispatch(card, state)
    assert result == {"modify_attack_power": 1}  # Effect should apply because there is less than 2 non-equipment cards in defense

# --- blessing_of_deliverance_blue ---
def test_blessing_of_deliverance_blue_draws_on_enter_play():
    # Mock state setup
    card = get_card("blessing_of_deliverance_blue")
    pitch_zone = [{"cost": 4}, {"cost": 2}]
    hand = []
    
    # Dispatch the effect
    dispatch(card, "ON_ENTER_PLAY", pitch_zone=pitch_zone, hand=hand)
    
    # Check if a card was drawn
    assert len(hand) == 1

def test_blessing_of_deliverance_blue_does_not_draw_on_enter_play():
    # Mock state setup
    card = get_card("blessing_of_deliverance_blue")
    pitch_zone = [{"cost": 2}, {"cost": 1}]
    hand = []
    
    # Dispatch the effect
    dispatch(card, "ON_ENTER_PLAY", pitch_zone=pitch_zone, hand=hand)
    
    # Check if no card was drawn
    assert len(hand) == 0

def test_blessing_of_deliverance_blue_gains_life_on_start_of_turn():
    # Mock state setup
    card = get_card("blessing_of_deliverance_blue")
    deck = [{"cost": 4}, {"cost": 2}]
    hand = []
    life_total = 10
    
    # Dispatch the effect
    dispatch(card, "START_OF_TURN", deck=deck, hand=hand, life_total=life_total)
    
    # Check if life total increased by 1 for each card with cost >= 3
    assert life_total == 12

def test_blessing_of_deliverance_blue_does_not_gain_life_on_start_of_turn():
    # Mock state setup
    card = get_card("blessing_of_deliverance_blue")
    deck = [{"cost": 2}, {"cost": 1}]
    hand = []
    life_total = 10
    
    # Dispatch the effect
    dispatch(card, "START_OF_TURN", deck=deck, hand=hand, life_total=life_total)
    
    # Check if life total did not change
    assert life_total == 10

# --- blessing_of_deliverance_red ---
def test_blessing_of_deliverance_red_draws_on_enter_play():
    # Mock state setup
    card = get_card("blessing_of_deliverance_red")
    pitch_zone = [{"cost": 4}, {"cost": 2}]
    hand_size = 5
    
    # Dispatch the effect
    new_state = dispatch(card, "ON_ENTER_PLAY", {
        "pitch_zone": pitch_zone,
        "hand_size": hand_size
    })
    
    # Assertions
    assert new_state["hand_size"] == hand_size + 1

def test_blessing_of_deliverance_red_gains_life_at_start_of_turn():
    # Mock state setup
    card = get_card("blessing_of_deliverance_red")
    deck = [{"cost": 4}, {"cost": 2}, {"cost": 5}]
    life_total = 10
    
    # Dispatch the effect
    new_state = dispatch(card, "START_OF_TURN", {
        "deck": deck,
        "life_total": life_total
    })
    
    # Assertions
    assert new_state["life_total"] == life_total + 2

def test_blessing_of_deliverance_red_does_not_gain_life_if_no_high_cost_cards():
    # Mock state setup
    card = get_card("blessing_of_deliverance_red")
    deck = [{"cost": 1}, {"cost": 2}, {"cost": 3}]
    life_total = 10
    
    # Dispatch the effect
    new_state = dispatch(card, "START_OF_TURN", {
        "deck": deck,
        "life_total": life_total
    })
    
    # Assertions
    assert new_state["life_total"] == life_total

# --- blessing_of_deliverance_yellow ---
def test_blessing_of_deliverance_yellow_draw_on_enter_play():
    # Mock state setup
    card = get_card("blessing_of_deliverance_yellow")
    player_state = {
        "pitch": [{"cost": 4}, {"cost": 2}],
        "hand": [],
        "deck": [{"cost": 5}, {"cost": 1}]
    }
    
    # Dispatch the ON_ENTER_PLAY trigger
    dispatch(card, "ON_ENTER_PLAY", player_state)
    
    # Check if a card was drawn
    assert len(player_state["hand"]) == 1

def test_blessing_of_deliverance_yellow_gain_life_on_start_of_turn():
    # Mock state setup
    card = get_card("blessing_of_deliverance_yellow")
    player_state = {
        "life": 20,
        "deck": [{"cost": 5}, {"cost": 1}, {"cost": 6}],
        "discard_pile": []
    }
    
    # Dispatch the START_OF_TURN trigger
    dispatch(card, "START_OF_TURN", player_state)
    
    # Check if Blessing of Deliverance was destroyed and life gained
    assert card not in player_state["pitch"]
    assert player_state["life"] == 21

def test_blessing_of_deliverance_yellow_no_draw_on_enter_play():
    # Mock state setup
    card = get_card("blessing_of_deliverance_yellow")
    player_state = {
        "pitch": [{"cost": 2}, {"cost": 1}],
        "hand": [],
        "deck": [{"cost": 5}, {"cost": 1}]
    }
    
    # Dispatch the ON_ENTER_PLAY trigger
    dispatch(card, "ON_ENTER_PLAY", player_state)
    
    # Check if no card was drawn
    assert len(player_state["hand"]) == 0

# --- bone_head_barrier_yellow ---
def test_bone_head_barrier_yellow_ability_fires_on_correct_trigger():
    # Mock state setup
    mock_state = {
        "hero": {"damage_taken": 0},
        "flags": {},
        "triggers": []
    }
    
    # Play the card
    card = get_card("bone_head_barrier_yellow")
    dispatch({"type": "PLAY", "card": card}, mock_state)
    
    # Simulate a defend trigger
    dispatch({"type": "DEFEND"}, mock_state)
    
    # Check if the ward effect was applied
    assert mock_state["hero"]["damage_taken"] == 0

def test_bone_head_barrier_yellow_condition_gates_correctly():
    # Mock state setup
    mock_state = {
        "hero": {"damage_taken": 0},
        "flags": {},
        "triggers": []
    }
    
    # Play the card
    card = get_card("bone_head_barrier_yellow")
    dispatch({"type": "PLAY", "card": card}, mock_state)
    
    # Simulate a defend trigger without the flag set
    dispatch({"type": "DEFEND"}, mock_state)
    
    # Check if the ward effect was not applied
    assert mock_state["hero"]["damage_taken"] == 0

def test_bone_head_barrier_yellow_effect_produces_expected_state_change():
    # Mock state setup
    mock_state = {
        "hero": {"damage_taken": 0},
        "flags": {},
        "triggers": []
    }
    
    # Play the card
    card = get_card("bone_head_barrier_yellow")
    dispatch({"type": "PLAY", "card": card}, mock_state)
    
    # Set the flag to simulate the condition being met
    mock_state["flags"]["bone_head_barrier_active"] = True
    
    # Simulate a defend trigger with the flag set
    dispatch({"type": "DEFEND"}, mock_state)
    
    # Check if the ward effect was applied
    assert mock_state["hero"]["damage_taken"] == 0

# --- braveforge_bracers ---
def test_braveforge_bracers_ability_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("braveforge_bracers")
    state = {
        "resources": 1,
        "weapon_hit_this_turn": True,
        "next_weapon_attack_bonus": 0
    }
    
    # Dispatch the ability
    dispatch(card, state)
    
    # Check if the bonus was applied and go_again is set
    assert state["next_weapon_attack_bonus"] == 1
    assert state.get("go_again", False) == True

def test_braveforge_bracers_condition_gates_correctly():
    # Mock state setup where condition should fail
    card = get_card("braveforge_bracers")
    state = {
        "resources": 1,
        "weapon_hit_this_turn": False,  # Condition fails here
        "next_weapon_attack_bonus": 0
    }
    
    # Dispatch the ability
    dispatch(card, state)
    
    # Check if no changes were made
    assert state["next_weapon_attack_bonus"] == 0
    assert "go_again" not in state

def test_braveforge_bracers_effect_produces_expected_state_change():
    # Mock state setup with multiple resources
    card = get_card("braveforge_bracers")
    state = {
        "resources": 2,
        "weapon_hit_this_turn": True,
        "next_weapon_attack_bonus": 0
    }
    
    # Dispatch the ability twice
    dispatch(card, state)
    dispatch(card, state)
    
    # Check if the bonus was applied and go_again is set each time
    assert state["next_weapon_attack_bonus"] == 1
    assert state.get("go_again", False) == True

# --- bravo ---
def test_bravo_ability_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("bravo")
    player_state = {
        "hand": [
            {"name": "Attack Card 1", "cost": 3},
            {"name": "Attack Card 2", "cost": 2}
        ],
        "resources": 5,
        "go_again": False
    }
    
    # Dispatch the ability
    dispatch(card, player_state)
    
    # Check if go_again is set to True
    assert player_state["go_again"] == True

def test_bravo_condition_gates_correctly():
    # Mock state setup
    card = get_card("bravo")
    player_state = {
        "hand": [
            {"name": "Attack Card 1", "cost": 3},
            {"name": "Attack Card 2", "cost": 2}
        ],
        "resources": 5,
        "go_again": False
    }
    
    # Dispatch the ability
    dispatch(card, player_state)
    
    # Check if only cards with cost >= 3 have dominate keyword
    for card in player_state["hand"]:
        if card["cost"] >= 3:
            assert "dominate" in card
        else:
            assert "dominate" not in card

def test_bravo_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("bravo")
    player_state = {
        "hand": [
            {"name": "Attack Card 1", "cost": 3},
            {"name": "Attack Card 2", "cost": 2}
        ],
        "resources": 5,
        "go_again": False
    }
    
    # Dispatch the ability
    dispatch(card, player_state)
    
    # Check if resources are reduced by 2 and go_again is set to True
    assert player_state["resources"] == 3
    assert player_state["go_again"] == True

# --- bravo_showstopper ---
def test_bravo_showstopper_ability_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("bravo_showstopper")
    state = {
        "player": {
            "resources": 2,
            "attack_action_cards": [
                {"cost": 3},
                {"cost": 2}
            ]
        }
    }
    
    # Dispatch the ability
    dispatch(card, state)
    
    # Check if the attack action card with cost 3 or greater has dominate keyword
    assert any(card["cost"] >= 3 and "dominate" in card.get("keywords", []) for card in state["player"]["attack_action_cards"])
    
    # Check if go again effect is applied (assuming it modifies a flag or similar)
    assert state["player"].get("go_again") == True

def test_bravo_showstopper_condition_gates_correctly():
    # Mock state setup
    card = get_card("bravo_showstopper")
    state = {
        "player": {
            "resources": 2,
            "attack_action_cards": [
                {"cost": 3},
                {"cost": 2}
            ]
        }
    }
    
    # Dispatch the ability
    dispatch(card, state)
    
    # Check if only attack action card with cost 3 or greater has dominate keyword
    assert any(card["cost"] >= 3 and "dominate" in card.get("keywords", []) for card in state["player"]["attack_action_cards"])
    assert not any(card["cost"] < 3 and "dominate" in card.get("keywords", []) for card in state["player"]["attack_action_cards"])

def test_bravo_showstopper_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("bravo_showstopper")
    state = {
        "player": {
            "resources": 2,
            "attack_action_cards": [
                {"cost": 3},
                {"cost": 4}
            ]
        }
    }
    
    # Dispatch the ability
    dispatch(card, state)
    
    # Check if both attack action cards with cost 3 or greater have dominate keyword
    assert all(card["cost"] >= 3 and "dominate" in card.get("keywords", []) for card in state["player"]["attack_action_cards"])

# --- breaking_scales ---
def test_breaking_scales_attack_reaction():
    # Mock state setup
    card = get_card("breaking_scales")
    attack_action = {
        "type": "ATTACK_ACTION",
        "combo": True,
        "power": 3
    }
    
    # Dispatch the attack reaction ability
    new_state = dispatch(card, "ATTACK_REACTION", attack_action)
    
    # Verify the effect: power should be increased by 1
    assert new_state["power"] == 4

def test_breaking_scales_activate():
    # Mock state setup
    card = get_card("breaking_scales")
    player_hand = [card]
    
    # Dispatch the activate ability
    new_state = dispatch(card, "ACTIVATE", player_hand)
    
    # Verify the effect: card should be destroyed (removed from hand)
    assert card not in new_state["hand"]

def test_breaking_scales_no_combo():
    # Mock state setup
    card = get_card("breaking_scales")
    attack_action = {
        "type": "ATTACK_ACTION",
        "combo": False,
        "power": 3
    }
    
    # Dispatch the attack reaction ability with no combo
    new_state = dispatch(card, "ATTACK_REACTION", attack_action)
    
    # Verify the effect: power should remain unchanged
    assert new_state["power"] == 3

# --- buckling_blow_blue ---
def test_buckling_blow_blue_ability_fires_on_hit():
    # Mock state setup
    card = get_card("buckling_blow_blue")
    hero = {
        "equipment": [
            {"name": "Equipment1", "counters": []}
        ]
    }
    context = {
        "card": card,
        "target": hero,
        "damage_amount": 4
    }

    # Dispatch the effect
    dispatch(card, context)

    # Check if the counter was added correctly
    assert hero["equipment"][0]["counters"] == [{"type": "-1d", "amount": 1}]

def test_buckling_blow_blue_condition_gates_correctly():
    # Mock state setup
    card = get_card("buckling_blow_blue")
    hero = {
        "equipment": [
            {"name": "Equipment1", "counters": []}
        ]
    }
    context = {
        "card": card,
        "target": hero,
        "damage_amount": 3  # Less than the required 4 damage
    }

    # Dispatch the effect
    dispatch(card, context)

    # Check if no counter was added
    assert hero["equipment"][0]["counters"] == []

def test_buckling_blow_blue_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("buckling_blow_blue")
    hero = {
        "equipment": [
            {"name": "Equipment1", "counters": []}
        ]
    }
    context = {
        "card": card,
        "target": hero,
        "damage_amount": 4
    }

    # Dispatch the effect
    dispatch(card, context)

    # Check if the counter was added correctly
    assert hero["equipment"][0]["counters"] == [{"type": "-1d", "amount": 1}]

# --- buckling_blow_red ---
def test_buckling_blow_red_ability_fires_on_hit():
    card = get_card("buckling_blow_red")
    state = {
        "hero": {
            "equipment": [
                {"name": "Equipment 1", "counters": []}
            ]
        }
    }
    
    # Simulate a hit that deals 4 damage
    event = {
        "type": "ON_HIT",
        "damage": 4,
        "target": state["hero"]
    }
    
    dispatch(card, event, state)
    
    # Check if the -1{d} counter was added to the equipment
    assert state["hero"]["equipment"][0]["counters"] == ["-1{d}"]

def test_buckling_blow_red_condition_gates_correctly():
    card = get_card("buckling_blow_red")
    state = {
        "hero": {
            "equipment": [
                {"name": "Equipment 1", "counters": []}
            ]
        }
    }
    
    # Simulate a hit that deals less than 4 damage
    event = {
        "type": "ON_HIT",
        "damage": 3,
        "target": state["hero"]
    }
    
    dispatch(card, event, state)
    
    # Check if no counter was added to the equipment
    assert state["hero"]["equipment"][0]["counters"] == []

def test_buckling_blow_red_effect_produces_expected_state_change():
    card = get_card("buckling_blow_red")
    state = {
        "hero": {
            "equipment": [
                {"name": "Equipment 1", "counters": []}
            ]
        }
    }
    
    # Simulate a hit that deals exactly 4 damage
    event = {
        "type": "ON_HIT",
        "damage": 4,
        "target": state["hero"]
    }
    
    dispatch(card, event, state)
    
    # Check if the -1{d} counter was added to the equipment
    assert state["hero"]["equipment"][0]["counters"] == ["-1{d}"]

# --- buckling_blow_yellow ---
def test_buckling_blow_yellow_ability_fires_on_hit():
    # Mock state setup
    card = get_card("buckling_blow_yellow")
    hero = {"equipment": [{"counter_type": "-1d", "amount": 0}]}
    
    # Simulate a hit that deals 4 damage
    context = {
        "trigger": "ON_HIT",
        "damage_amount": 4,
        "hero": hero
    }
    
    # Dispatch the ability
    dispatch(card, context)
    
    # Check if the -1d counter was added
    assert hero["equipment"][0]["amount"] == 1

def test_buckling_blow_yellow_condition_gates_correctly():
    # Mock state setup
    card = get_card("buckling_blow_yellow")
    hero = {"equipment": [{"counter_type": "-1d", "amount": 0}]}
    
    # Simulate a hit that deals less than 4 damage
    context = {
        "trigger": "ON_HIT",
        "damage_amount": 3,
        "hero": hero
    }
    
    # Dispatch the ability
    dispatch(card, context)
    
    # Check if no -1d counter was added
    assert hero["equipment"][0]["amount"] == 0

def test_buckling_blow_yellow_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("buckling_blow_yellow")
    hero = {"equipment": [{"counter_type": "-1d", "amount": 0}]}
    
    # Simulate a hit that deals exactly 4 damage
    context = {
        "trigger": "ON_HIT",
        "damage_amount": 4,
        "hero": hero
    }
    
    # Dispatch the ability
    dispatch(card, context)
    
    # Check if the -1d counter was added
    assert hero["equipment"][0]["amount"] == 1

# --- cartilage_crush_blue ---
def test_cartilage_crush_blue_ability_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("cartilage_crush_blue")
    hero = {"slug": "mock_hero", "actions": [{"cost": 0}]}
    attacker = {"slug": "mock_attacker", "damage": 5}
    
    # Trigger the ability
    dispatch(card, "ON_HIT", {"attacker": attacker, "target": hero})
    
    # Check if the flag is set correctly
    assert hero.get("crush_cost_next_turn") == True

def test_cartilage_crush_blue_condition_gates_correctly():
    # Mock state setup
    card = get_card("cartilage_crush_blue")
    hero = {"slug": "mock_hero", "actions": [{"cost": 0}]}
    attacker = {"slug": "mock_attacker", "damage": 3}
    
    # Trigger the ability with less than 4 damage
    dispatch(card, "ON_HIT", {"attacker": attacker, "target": hero})
    
    # Check if the flag is not set
    assert "crush_cost_next_turn" not in hero

def test_cartilage_crush_blue_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("cartilage_crush_blue")
    hero = {"slug": "mock_hero", "actions": [{"cost": 0}]}
    attacker = {"slug": "mock_attacker", "damage": 4}
    
    # Trigger the ability with exactly 4 damage
    dispatch(card, "ON_HIT", {"attacker": attacker, "target": hero})
    
    # Check if the flag is set correctly
    assert hero.get("crush_cost_next_turn") == True

# --- cartilage_crush_red ---
def test_cartilage_crush_red_ability_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("cartilage_crush_red")
    hero = {"slug": "mock_hero", "actions": [{"cost": 0}]}
    damage_info = {"damage": 4, "target": hero}

    # Dispatch the effect
    dispatch(card, "ON_HIT", damage_info)

    # Check if the flag is set correctly
    assert hero.get("crush_cost_next_turn") == True

def test_cartilage_crush_red_condition_gates_correctly():
    # Mock state setup
    card = get_card("cartilage_crush_red")
    hero = {"slug": "mock_hero", "actions": [{"cost": 0}]}
    damage_info_passing = {"damage": 4, "target": hero}
    damage_info_failing = {"damage": 3, "target": hero}

    # Dispatch the effect with passing condition
    dispatch(card, "ON_HIT", damage_info_passing)
    assert hero.get("crush_cost_next_turn") == True

    # Reset state and dispatch with failing condition
    del hero["crush_cost_next_turn"]
    dispatch(card, "ON_HIT", damage_info_failing)
    assert "crush_cost_next_turn" not in hero

def test_cartilage_crush_red_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("cartilage_crush_red")
    hero = {"slug": "mock_hero", "actions": [{"cost": 0}]}
    damage_info = {"damage": 4, "target": hero}

    # Dispatch the effect
    dispatch(card, "ON_HIT", damage_info)

    # Check if the flag is set correctly
    assert hero.get("crush_cost_next_turn") == True

    # Simulate next turn action cost increase
    for action in hero["actions"]:
        if action["cost"] == 0:
            action["cost"] += 1

    # Verify the action cost has increased
    assert hero["actions"][0]["cost"] == 1

# --- cartilage_crush_yellow ---
def test_cartilage_crush_yellow_ability_fires_on_correct_trigger():
    card = get_card("cartilage_crush_yellow")
    state = {
        "hero": {
            "actions": [
                {"name": "Action 1", "cost": 2},
                {"name": "Action 2", "cost": 3}
            ]
        }
    }
    event = {
        "type": "ON_HIT",
        "damage": 5,
        "target": "hero"
    }
    dispatch(card, state, event)
    assert state["hero"]["actions"][0]["cost"] == 3
    assert state["hero"]["actions"][1]["cost"] == 4

def test_cartilage_crush_yellow_condition_gates_correctly():
    card = get_card("cartilage_crush_yellow")
    state = {
        "hero": {
            "actions": [
                {"name": "Action 1", "cost": 2},
                {"name": "Action 2", "cost": 3}
            ]
        }
    }
    event = {
        "type": "ON_HIT",
        "damage": 3,
        "target": "hero"
    }
    dispatch(card, state, event)
    assert state["hero"]["actions"][0]["cost"] == 2
    assert state["hero"]["actions"][1]["cost"] == 3

def test_cartilage_crush_yellow_effect_produces_expected_state_change():
    card = get_card("cartilage_crush_yellow")
    state = {
        "hero": {
            "actions": [
                {"name": "Action 1", "cost": 2},
                {"name": "Action 2", "cost": 3}
            ]
        }
    }
    event = {
        "type": "ON_HIT",
        "damage": 4,
        "target": "hero"
    }
    dispatch(card, state, event)
    assert state["hero"]["actions"][0]["cost"] == 3
    assert state["hero"]["actions"][1]["cost"] == 4

# --- cracked_bauble_yellow ---
def test_cracked_bauble_yellow_no_abilities():
    card = get_card("cracked_bauble_yellow")
    assert not card.abilities, "Cracked Bauble should have no abilities"

def test_cracked_bauble_yellow_add_to_deck():
    # Mock state setup
    player_deck = []
    card = get_card("cracked_bauble_yellow")
    
    # Simulate adding Cracked Baubles to the deck
    for _ in range(3):
        dispatch(card, "add_to_deck", player_deck)
    
    assert len(player_deck) == 3, "Player's deck should have 3 Cracked Baubles"
    assert all(c["slug"] == "cracked_bauble_yellow" for c in player_deck), "All cards in the deck should be Cracked Baubles"

def test_cracked_bauble_yellow_add_to_draft():
    # Mock state setup
    draft_pool = []
    card = get_card("cracked_bauble_yellow")
    
    # Simulate adding Cracked Baubles to the draft pool
    for _ in range(5):
        dispatch(card, "add_to_draft", draft_pool)
    
    assert len(draft_pool) == 5, "Draft pool should have 5 Cracked Baubles"
    assert all(c["slug"] == "cracked_bauble_yellow" for c in draft_pool), "All cards in the draft pool should be Cracked Baubles"

# --- cranial_crush_blue ---
def test_cranial_crush_blue_ability_fires_on_hit():
    card = get_card("cranial_crush_blue")
    state = {
        "hero": {
            "no_draw_next_action": False,
            "damage_taken": 0
        }
    }
    
    # Simulate a hit that deals 4 damage
    dispatch(card, "ON_HIT", {"damage_amount": 4}, state)
    
    assert state["hero"]["no_draw_next_action"] == True

def test_cranial_crush_blue_condition_gates_correctly():
    card = get_card("cranial_crush_blue")
    state = {
        "hero": {
            "no_draw_next_action": False,
            "damage_taken": 0
        }
    }
    
    # Simulate a hit that deals less than 4 damage
    dispatch(card, "ON_HIT", {"damage_amount": 3}, state)
    
    assert state["hero"]["no_draw_next_action"] == False

def test_cranial_crush_blue_effect_produces_expected_state_change():
    card = get_card("cranial_crush_blue")
    state = {
        "hero": {
            "no_draw_next_action": False,
            "damage_taken": 0
        }
    }
    
    # Simulate a hit that deals exactly 4 damage
    dispatch(card, "ON_HIT", {"damage_amount": 4}, state)
    
    assert state["hero"]["no_draw_next_action"] == True

# --- crazy_brew_blue ---
def test_crazy_brew_blue_ability_fires_on_activate():
    card = get_card("crazy_brew_blue")
    state = {
        "player": {
            "health": 20,
            "action_points": 3
        },
        "opponent": {
            "health": 20
        }
    }
    result = dispatch(card, "ACTIVATE", state)
    assert result["player"]["action_points"] == 5

def test_crazy_brew_blue_gains_resources_on_5_or_6():
    card = get_card("crazy_brew_blue")
    state = {
        "player": {
            "health": 20,
            "resources": {"r": 0},
            "action_points": 3
        },
        "opponent": {
            "health": 20
        }
    }
    result = dispatch(card, "ACTIVATE", state)
    assert result["player"]["resources"] == {"r": 2}
    assert result["player"]["action_points"] == 5

def test_crazy_brew_blue_next_attack_bonus_on_5_or_6():
    card = get_card("crazy_brew_blue")
    state = {
        "player": {
            "health": 20,
            "resources": {"r": 0},
            "action_points": 3
        },
        "opponent": {
            "health": 20
        }
    }
    result = dispatch(card, "ACTIVATE", state)
    assert result["player"]["next_attack_bonus"] == 2

# --- crippling_crush_red ---
def test_crippling_crush_red_ability_fires_on_hit():
    # Mock state setup
    card = get_card("crippling_crush_red")
    hero = {"health": 10, "deck": [1, 2, 3, 4, 5], "hand": [6, 7]}
    opponent = {"deck": [], "hand": [8, 9, 10]}

    # Simulate a hit that deals 4 damage
    event = {
        "type": "ON_HIT",
        "damage": 4,
        "target": hero,
        "attacker": card
    }

    # Dispatch the event
    dispatch(event)

    # Check if the opponent discarded 2 cards
    assert len(opponent["hand"]) == 1

def test_crippling_crush_red_condition_gates_correctly():
    # Mock state setup
    card = get_card("crippling_crush_red")
    hero = {"health": 10, "deck": [1, 2, 3, 4, 5], "hand": [6, 7]}
    opponent = {"deck": [], "hand": [8, 9, 10]}

    # Simulate a hit that deals less than 4 damage
    event = {
        "type": "ON_HIT",
        "damage": 3,
        "target": hero,
        "attacker": card
    }

    # Dispatch the event
    dispatch(event)

    # Check if the opponent did not discard any cards
    assert len(opponent["hand"]) == 3

def test_crippling_crush_red_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("crippling_crush_red")
    hero = {"health": 10, "deck": [1, 2, 3, 4, 5], "hand": [6, 7]}
    opponent = {"deck": [], "hand": [8, 9, 10]}

    # Simulate a hit that deals 4 damage
    event = {
        "type": "ON_HIT",
        "damage": 4,
        "target": hero,
        "attacker": card
    }

    # Dispatch the event
    dispatch(event)

    # Check if the opponent discarded 2 cards
    assert len(opponent["hand"]) == 1

# --- crush_confidence_blue ---
def test_crush_confidence_blue_ability_fires_on_correct_trigger():
    card = get_card("crush_confidence_blue")
    hero = {
        "abilities": ["ability1", "ability2"],
        "hero_abilities_disabled": False
    }
    state = {
        "card": card,
        "hero": hero,
        "damage_dealt": 4
    }
    
    dispatch(state)
    
    assert hero["hero_abilities_disabled"] == True

def test_crush_confidence_blue_condition_gates_correctly():
    card = get_card("crush_confidence_blue")
    hero = {
        "abilities": ["ability1", "ability2"],
        "hero_abilities_disabled": False
    }
    state = {
        "card": card,
        "hero": hero,
        "damage_dealt": 3
    }
    
    dispatch(state)
    
    assert hero["hero_abilities_disabled"] == False

def test_crush_confidence_blue_effect_produces_expected_state_change():
    card = get_card("crush_confidence_blue")
    hero = {
        "abilities": ["ability1", "ability2"],
        "hero_abilities_disabled": False
    }
    state = {
        "card": card,
        "hero": hero,
        "damage_dealt": 4
    }
    
    dispatch(state)
    
    assert hero["hero_abilities_disabled"] == True

# --- crush_confidence_red ---
def test_crush_confidence_red_ability_fires_on_hit():
    # Mock state setup
    card = get_card("crush_confidence_red")
    hero = {"hero_card_abilities_disabled": False}
    attack_result = {"damage": 5}

    # Dispatch the effect
    dispatch(card, "ON_HIT", hero, attack_result)

    # Check if the ability fired correctly
    assert hero["hero_card_abilities_disabled"] is True

def test_crush_confidence_red_condition_gates_correctly():
    # Mock state setup
    card = get_card("crush_confidence_red")
    hero = {"hero_card_abilities_disabled": False}
    attack_result = {"damage": 3}

    # Dispatch the effect
    dispatch(card, "ON_HIT", hero, attack_result)

    # Check if the condition gated correctly
    assert hero["hero_card_abilities_disabled"] is False

def test_crush_confidence_red_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("crush_confidence_red")
    hero = {"hero_card_abilities_disabled": False}
    attack_result = {"damage": 4}

    # Dispatch the effect
    dispatch(card, "ON_HIT", hero, attack_result)

    # Check if the effect produced the expected state change
    assert hero["hero_card_abilities_disabled"] is True

# --- crush_confidence_yellow ---
def test_crush_confidence_yellow_ability_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("crush_confidence_yellow")
    hero = {
        "abilities": ["ability1", "ability2"],
        "flags": {}
    }
    attack_info = {
        "damage": 5,
        "target": hero
    }

    # Dispatch the effect
    dispatch(card, attack_info)

    # Check if the flag is set correctly
    assert "crush_confidence_lose_ability" in hero["flags"]

def test_crush_confidence_yellow_condition_gates_correctly():
    # Mock state setup
    card = get_card("crush_confidence_yellow")
    hero = {
        "abilities": ["ability1", "ability2"],
        "flags": {}
    }
    attack_info = {
        "damage": 3,
        "target": hero
    }

    # Dispatch the effect
    dispatch(card, attack_info)

    # Check if the flag is not set when condition fails
    assert "crush_confidence_lose_ability" not in hero["flags"]

def test_crush_confidence_yellow_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("crush_confidence_yellow")
    hero = {
        "abilities": ["ability1", "ability2"],
        "flags": {}
    }
    attack_info = {
        "damage": 4,
        "target": hero
    }

    # Dispatch the effect
    dispatch(card, attack_info)

    # Check if the flag is set correctly when condition passes
    assert "crush_confidence_lose_ability" in hero["flags"]

# --- dawnblade ---
def test_dawnblade_attack_first_hit():
    card = get_card("dawnblade")
    state = {
        "flags": {},
        "counters": {}
    }
    
    # Simulate the first attack
    state = dispatch(card, "ON_ATTACK", state)
    
    assert state["flags"]["dawnblade_hit"] == True
    assert "dawnblade_second_hit" not in state["flags"]
    assert "dawnblade" not in state["counters"]

def test_dawnblade_attack_second_hit():
    card = get_card("dawnblade")
    state = {
        "flags": {"dawnblade_hit": True},
        "counters": {}
    }
    
    # Simulate the second attack
    state = dispatch(card, "ON_ATTACK", state)
    
    assert state["flags"]["dawnblade_second_hit"] == True
    assert state["counters"]["dawnblade"] == {"+1p": 1}

def test_dawnblade_end_phase_no_hits():
    card = get_card("dawnblade")
    state = {
        "flags": {},
        "counters": {"dawnblade": {"+1p": 2}}
    }
    
    # Simulate the end of turn
    state = dispatch(card, "START_OF_TURN", state)
    
    assert "dawnblade" not in state["counters"]

# --- debilitate_blue ---
def test_debilitate_blue_ability_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("debilitate_blue")
    hero = {"name": "Hero", "attack_power": 10}
    attacker = {"name": "Attacker"}
    
    # Simulate a hit that deals 4 damage
    state = {
        "hero": hero,
        "attacker": attacker,
        "damage_dealt": 4
    }
    
    # Dispatch the effect
    dispatch(card, state)
    
    # Check if the attack power is modified correctly
    assert hero["attack_power"] == 8

def test_debilitate_blue_condition_gates_correctly():
    # Mock state setup
    card = get_card("debilitate_blue")
    hero = {"name": "Hero", "attack_power": 10}
    attacker = {"name": "Attacker"}
    
    # Simulate a hit that deals less than 4 damage
    state = {
        "hero": hero,
        "attacker": attacker,
        "damage_dealt": 3
    }
    
    # Dispatch the effect
    dispatch(card, state)
    
    # Check if the attack power is not modified
    assert hero["attack_power"] == 10

def test_debilitate_blue_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("debilitate_blue")
    hero = {"name": "Hero", "attack_power": 10}
    attacker = {"name": "Attacker"}
    
    # Simulate a hit that deals exactly 4 damage
    state = {
        "hero": hero,
        "attacker": attacker,
        "damage_dealt": 4
    }
    
    # Dispatch the effect
    dispatch(card, state)
    
    # Check if the attack power is modified correctly
    assert hero["attack_power"] == 8

# --- debilitate_red ---
def test_debilitate_red_ability_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("debilitate_red")
    hero = {
        "attacks": [
            {"power": 5},
            {"power": 3}
        ]
    }
    damage = 4

    # Dispatch the effect
    dispatch(card, "ON_HIT", hero, damage)

    # Check if the next attack power is modified correctly
    assert hero["attacks"][0]["power"] == 3  # First attack should have -2 power
    assert hero["attacks"][1]["power"] == 3  # Second attack remains unchanged

def test_debilitate_red_condition_gates_correctly():
    # Mock state setup
    card = get_card("debilitate_red")
    hero = {
        "attacks": [
            {"power": 5},
            {"power": 3}
        ]
    }
    damage = 3  # Less than the required 4 to trigger

    # Dispatch the effect
    dispatch(card, "ON_HIT", hero, damage)

    # Check if the next attack power is not modified
    assert hero["attacks"][0]["power"] == 5  # First attack should remain unchanged
    assert hero["attacks"][1]["power"] == 3  # Second attack remains unchanged

def test_debilitate_red_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("debilitate_red")
    hero = {
        "attacks": [
            {"power": 6},
            {"power": 2}
        ]
    }
    damage = 5  # More than the required 4 to trigger

    # Dispatch the effect
    dispatch(card, "ON_HIT", hero, damage)

    # Check if the next attack power is modified correctly
    assert hero["attacks"][0]["power"] == 4  # First attack should have -2 power
    assert hero["attacks"][1]["power"] == 2  # Second attack remains unchanged

# --- debilitate_yellow ---
def test_debilitate_yellow_ability_fires_on_correct_trigger():
    # Mock state setup
    mock_state = {
        "hero": {
            "health": 10,
            "attack_power": 5
        },
        "active_player": True
    }
    
    # Simulate a hit with 4 damage
    result = dispatch("debilitate_yellow", "ON_HIT", {"damage": 4}, mock_state)
    
    # Check if the ability fired and injected the trigger correctly
    assert "INJECT_TRIGGER" in result["effects"]
    assert result["effects"]["INJECT_TRIGGER"]["trigger"] == "ON_ATTACK"
    assert result["effects"]["INJECT_TRIGGER"]["conditions"][0]["type"] == "IS_ACTIVE_PLAYER"

def test_debilitate_yellow_condition_gates_correctly():
    # Mock state setup
    mock_state = {
        "hero": {
            "health": 10,
            "attack_power": 5
        },
        "active_player": True
    }
    
    # Simulate a hit with less than 4 damage
    result = dispatch("debilitate_yellow", "ON_HIT", {"damage": 3}, mock_state)
    
    # Check if the ability did not fire due to condition gate
    assert "INJECT_TRIGGER" not in result["effects"]

def test_debilitate_yellow_effect_produces_expected_state_change():
    # Mock state setup
    mock_state = {
        "hero": {
            "health": 10,
            "attack_power": 5
        },
        "active_player": True
    }
    
    # Simulate a hit with 4 damage and then an attack
    dispatch("debilitate_yellow", "ON_HIT", {"damage": 4}, mock_state)
    result = dispatch("debilitate_yellow", "ON_ATTACK", {}, mock_state)
    
    # Check if the attack power was modified correctly
    assert result["hero"]["attack_power"] == 3

# --- demolition_crew_blue ---
def test_demolition_crew_blue_ability_fires_on_play():
    card = get_card("demolition_crew_blue")
    state = {
        "hand": [
            {"cost": 1},
            {"cost": 3}
        ]
    }
    result = dispatch(card, "PLAY", state)
    assert result["played"] == True
    assert result["revealed_card_cost"] >= 2

def test_demolition_crew_blue_condition_gates_correctly():
    card = get_card("demolition_crew_blue")
    state1 = {
        "hand": [
            {"cost": 1},
            {"cost": 1}
        ]
    }
    result1 = dispatch(card, "PLAY", state1)
    assert result1["played"] == False

    state2 = {
        "hand": [
            {"cost": 3},
            {"cost": 4}
        ]
    }
    result2 = dispatch(card, "PLAY", state2)
    assert result2["played"] == True
    assert result2["revealed_card_cost"] >= 2

def test_demolition_crew_blue_effect_produces_expected_state_change():
    card = get_card("demolition_crew_blue")
    state = {
        "hand": [
            {"cost": 3},
            {"cost": 4}
        ],
        "opponent_strength": 10
    }
    result = dispatch(card, "PLAY", state)
    assert result["played"] == True
    assert result["revealed_card_cost"] >= 2
    assert result["opponent_strength"] < 10  # Assuming DOMINATE reduces opponent strength

# --- demolition_crew_red ---
def test_demolition_crew_red_ability_fires():
    card = get_card("demolition_crew_red")
    state = {
        "player": {
            "hand": [
                {"cost": 1},
                {"cost": 3}
            ]
        }
    }
    # Reveal a card with cost 2 or greater
    revealed_card = state["player"]["hand"].pop(1)
    assert revealed_card["cost"] >= 2

    # Dispatch the play ability
    dispatch(card, "PLAY", state)

    # Check if the dominate effect was applied
    assert state.get("dominate_applied") is True

def test_demolition_crew_red_condition_gates_correctly():
    card = get_card("demolition_crew_red")
    state1 = {
        "player": {
            "hand": [
                {"cost": 1},
                {"cost": 1}
            ]
        }
    }
    # Reveal a card with cost less than 2
    revealed_card1 = state1["player"]["hand"].pop(0)
    assert revealed_card1["cost"] < 2

    # Dispatch the play ability
    dispatch(card, "PLAY", state1)

    # Check if the dominate effect was not applied due to condition failure
    assert state1.get("dominate_applied") is None

def test_demolition_crew_red_effect_produces_expected_state_change():
    card = get_card("demolition_crew_red")
    state2 = {
        "player": {
            "hand": [
                {"cost": 3},
                {"cost": 4}
            ]
        }
    }
    # Reveal a card with cost 2 or greater
    revealed_card2 = state2["player"]["hand"].pop(0)
    assert revealed_card2["cost"] >= 2

    # Dispatch the play ability
    dispatch(card, "PLAY", state2)

    # Check if the dominate effect was applied and state changed as expected
    assert state2.get("dominate_applied") is True

# --- demolition_crew_yellow ---
def test_demolition_crew_yellow_ability_fires_on_play():
    # Mock state setup
    card = get_card("demolition_crew_yellow")
    player_hand = [{"cost": 3}, {"cost": 1}]
    
    # Dispatch the play ability with a valid reveal cost
    result = dispatch(card, "PLAY", player_hand=player_hand)
    
    assert result["success"] == True

def test_demolition_crew_yellow_condition_gates_correctly():
    # Mock state setup
    card = get_card("demolition_crew_yellow")
    player_hand = [{"cost": 1}, {"cost": 1}]
    
    # Dispatch the play ability with an invalid reveal cost
    result = dispatch(card, "PLAY", player_hand=player_hand)
    
    assert result["success"] == False

def test_demolition_crew_yellow_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("demolition_crew_yellow")
    player_hand = [{"cost": 3}, {"cost": 1}]
    game_state = {"opponent_life_total": 20}
    
    # Dispatch the play ability with a valid reveal cost
    result = dispatch(card, "PLAY", player_hand=player_hand, game_state=game_state)
    
    assert result["game_state"]["opponent_life_total"] == 19

# --- disable_blue ---
def test_disable_blue_ability_fires_on_correct_trigger():
    # Mock state setup
    hero = {
        "arsenal": ["card1", "card2"],
        "deck": []
    }
    card = get_card("disable_blue")
    
    # Simulate a hit with 4 damage
    trigger_event = {
        "type": "ON_HIT",
        "damage": 4,
        "target": hero
    }
    
    # Dispatch the event
    dispatch(card, trigger_event)
    
    # Check if the card was put on the bottom of the deck
    assert hero["deck"] == ["card1"]
    assert hero["arsenal"] == ["card2"]

def test_disable_blue_condition_gates_correctly():
    # Mock state setup
    hero = {
        "arsenal": ["card1", "card2"],
        "deck": []
    }
    card = get_card("disable_blue")
    
    # Simulate a hit with 3 damage (should not trigger)
    trigger_event = {
        "type": "ON_HIT",
        "damage": 3,
        "target": hero
    }
    
    # Dispatch the event
    dispatch(card, trigger_event)
    
    # Check if no card was put on the bottom of the deck
    assert hero["deck"] == []
    assert hero["arsenal"] == ["card1", "card2"]

def test_disable_blue_effect_produces_expected_state_change():
    # Mock state setup
    hero = {
        "arsenal": ["card1", "card2"],
        "deck": []
    }
    card = get_card("disable_blue")
    
    # Simulate a hit with 5 damage (should trigger)
    trigger_event = {
        "type": "ON_HIT",
        "damage": 5,
        "target": hero
    }
    
    # Dispatch the event
    dispatch(card, trigger_event)
    
    # Check if the card was put on the bottom of the deck
    assert hero["deck"] == ["card1"]
    assert hero["arsenal"] == ["card2"]

# --- disable_red ---
def test_disable_red_ability_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("disable_red")
    hero = {
        "arsenal": ["card1", "card2", "card3"],
        "deck": []
    }
    opponent = {
        "arsenal": ["opponent_card1"],
        "deck": []
    }
    
    # Simulate a hit with 4 damage
    state = {
        "hero": hero,
        "opponent": opponent,
        "damage_dealt": 4
    }
    
    # Dispatch the effect
    dispatch(card, state)
    
    # Check if the card was moved to the bottom of the deck
    assert len(opponent["arsenal"]) == 0
    assert len(opponent["deck"]) == 1
    assert opponent["deck"][0] == "opponent_card1"

def test_disable_red_condition_gates_correctly():
    # Mock state setup
    card = get_card("disable_red")
    hero = {
        "arsenal": ["card1", "card2", "card3"],
        "deck": []
    }
    opponent = {
        "arsenal": ["opponent_card1"],
        "deck": []
    }
    
    # Simulate a hit with less than 4 damage
    state = {
        "hero": hero,
        "opponent": opponent,
        "damage_dealt": 3
    }
    
    # Dispatch the effect
    dispatch(card, state)
    
    # Check if no card was moved to the deck
    assert len(opponent["arsenal"]) == 1
    assert len(opponent["deck"]) == 0

def test_disable_red_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("disable_red")
    hero = {
        "arsenal": ["card1", "card2", "card3"],
        "deck": []
    }
    opponent = {
        "arsenal": ["opponent_card1"],
        "deck": []
    }
    
    # Simulate a hit with 4 damage
    state = {
        "hero": hero,
        "opponent": opponent,
        "damage_dealt": 4
    }
    
    # Dispatch the effect
    dispatch(card, state)
    
    # Check if the card was moved to the bottom of the deck
    assert len(opponent["arsenal"]) == 0
    assert len(opponent["deck"]) == 1
    assert opponent["deck"][0] == "opponent_card1"

# --- disable_yellow ---
def test_disable_yellow_ability_fires_on_correct_trigger():
    # Mock state setup
    mock_state = {
        "hero": {
            "arsenal": ["card1", "card2", "card3"],
            "deck": []
        },
        "damage_dealt": 4
    }
    
    card = get_card("disable_yellow")
    ability = card.abilities[0]
    
    # Dispatch the effect
    new_state = dispatch(mock_state, ability)
    
    # Check if a card was moved to the bottom of the deck
    assert len(new_state["hero"]["deck"]) == 1
    assert new_state["hero"]["deck"][0] in ["card1", "card2", "card3"]
    assert len(new_state["hero"]["arsenal"]) == 2

def test_disable_yellow_condition_gates_correctly():
    # Mock state setup for condition failure
    mock_state = {
        "hero": {
            "arsenal": ["card1", "card2", "card3"],
            "deck": []
        },
        "damage_dealt": 3
    }
    
    card = get_card("disable_yellow")
    ability = card.abilities[0]
    
    # Dispatch the effect
    new_state = dispatch(mock_state, ability)
    
    # Check if no card was moved to the bottom of the deck
    assert len(new_state["hero"]["deck"]) == 0
    assert len(new_state["hero"]["arsenal"]) == 3

def test_disable_yellow_effect_produces_expected_state_change():
    # Mock state setup for condition success
    mock_state = {
        "hero": {
            "arsenal": ["card1", "card2", "card3"],
            "deck": []
        },
        "damage_dealt": 4
    }
    
    card = get_card("disable_yellow")
    ability = card.abilities[0]
    
    # Dispatch the effect
    new_state = dispatch(mock_state, ability)
    
    # Check if a card was moved to the bottom of the deck
    assert len(new_state["hero"]["deck"]) == 1
    assert new_state["hero"]["deck"][0] in ["card1", "card2", "card3"]
    assert len(new_state["hero"]["arsenal"]) == 2

# --- dorinthea ---
def test_dorinthea_effect_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("dorinthea")
    state = {
        "flags": {},
        "last_hit": {"is_weapon": True}
    }
    
    # Dispatch the ON_HIT trigger
    dispatch(card, "ON_HIT", state)
    
    # Check if the flag is set and go_again effect is applied
    assert state["flags"]["dorinthea_used_this_turn"] == True
    assert state.get("go_again") == True

def test_dorinthea_effect_does_not_fire_when_condition_gates():
    # Mock state setup where Dorinthea has already been used this turn
    card = get_card("dorinthea")
    state = {
        "flags": {"dorinthea_used_this_turn": True},
        "last_hit": {"is_weapon": True}
    }
    
    # Dispatch the ON_HIT trigger
    dispatch(card, "ON_HIT", state)
    
    # Check if the flag remains set and go_again effect is not applied
    assert state["flags"]["dorinthea_used_this_turn"] == True
    assert "go_again" not in state

def test_dorinthea_effect_does_not_fire_on_non_weapon_attack():
    # Mock state setup with a non-weapon attack
    card = get_card("dorinthea")
    state = {
        "flags": {},
        "last_hit": {"is_weapon": False}
    }
    
    # Dispatch the ON_HIT trigger
    dispatch(card, "ON_HIT", state)
    
    # Check if the flag is not set and go_again effect is not applied
    assert "dorinthea_used_this_turn" not in state["flags"]
    assert "go_again" not in state

# --- dorinthea_ironsong ---
def test_dorinthea_ironsong_ability_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("dorinthea_ironsong")
    state = {
        "player": {
            "weapons": [
                {"name": "Mock Weapon", "attacks_this_turn": 0}
            ]
        }
    }
    
    # Trigger the ability
    event = {
        "type": "ATTACK",
        "weapon_name": "Mock Weapon"
    }
    dispatch(card, state, event)
    
    # Check if the weapon's attacks_this_turn was incremented
    assert state["player"]["weapons"][0]["attacks_this_turn"] == 1

def test_dorinthea_ironsong_condition_gates_correctly():
    # Mock state setup
    card = get_card("dorinthea_ironsong")
    state = {
        "player": {
            "weapons": [
                {"name": "Mock Weapon", "attacks_this_turn": 0}
            ]
        }
    }
    
    # Trigger the ability with a non-weapon attack
    event = {
        "type": "ATTACK",
        "weapon_name": None
    }
    dispatch(card, state, event)
    
    # Check if the weapon's attacks_this_turn was not incremented
    assert state["player"]["weapons"][0]["attacks_this_turn"] == 0

def test_dorinthea_ironsong_effect_produces_expected_state_change():
    # Mock state setup
    card = get_card("dorinthea_ironsong")
    state = {
        "player": {
            "weapons": [
                {"name": "Mock Weapon", "attacks_this_turn": 0}
            ]
        }
    }
    
    # Trigger the ability twice
    event = {
        "type": "ATTACK",
        "weapon_name": "Mock Weapon"
    }
    dispatch(card, state, event)
    dispatch(card, state, event)
    
    # Check if the weapon's attacks_this_turn was incremented only once
    assert state["player"]["weapons"][0]["attacks_this_turn"] == 1

# --- drone_of_brutality_blue ---
def test_drone_of_brutality_blue_ability_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("drone_of_brutality_blue")
    game_state = {
        "zones": {
            "graveyard": [card],
            "deck": []
        }
    }
    
    # Trigger the ability
    dispatch(game_state, "ON_LEAVE_PLAY", card)
    
    # Check if the card is on the bottom of the deck
    assert game_state["zones"]["graveyard"] == []
    assert game_state["zones"]["deck"] == [card]

def test_drone_of_brutality_blue_condition_gates_correctly():
    # Mock state setup where the card is not in the graveyard
    card = get_card("drone_of_brutality_blue")
    game_state = {
        "zones": {
            "graveyard": [],
            "deck": []
        }
    }
    
    # Trigger the ability
    dispatch(game_state, "ON_LEAVE_PLAY", card)
    
    # Check if the card is still not in the graveyard and deck remains empty
    assert game_state["zones"]["graveyard"] == []
    assert game_state["zones"]["deck"] == []

def test_drone_of_brutality_blue_effect_produces_expected_state_change():
    # Mock state setup with multiple cards, including Drone of Brutality
    card1 = get_card("drone_of_brutality_blue")
    card2 = {"slug": "other_card"}
    game_state = {
        "zones": {
            "graveyard": [card1, card2],
            "deck": []
        }
    }
    
    # Trigger the ability for Drone of Brutality
    dispatch(game_state, "ON_LEAVE_PLAY", card1)
    
    # Check if Drone of Brutality is on the bottom of the deck and other card remains in graveyard
    assert game_state["zones"]["graveyard"] == [card2]
    assert game_state["zones"]["deck"] == [card1]

# --- drone_of_brutality_red ---
def test_drone_of_brutality_red_ability_fires_on_correct_trigger():
    # Mock state setup
    card = {
        "slug": "drone_of_brutality_red",
        "name": "Drone of Brutality",
        "type": "Generic Action - Attack"
    }
    game_state = {
        "zones": {
            "graveyard": [card],
            "deck": []
        }
    }
    
    # Dispatch the trigger event
    dispatch("ON_LEAVE_PLAY", card, game_state)
    
    # Check if the card is now on the bottom of the deck
    assert len(game_state["zones"]["graveyard"]) == 0
    assert len(game_state["zones"]["deck"]) == 1
    assert game_state["zones"]["deck"][0] == card

def test_drone_of_brutality_red_condition_gates_correctly():
    # Mock state setup where the card is not in the graveyard
    card = {
        "slug": "drone_of_brutality_red",
        "name": "Drone of Brutality",
        "type": "Generic Action - Attack"
    }
    game_state = {
        "zones": {
            "graveyard": [],
            "deck": []
        }
    }
    
    # Dispatch the trigger event
    dispatch("ON_LEAVE_PLAY", card, game_state)
    
    # Check if the card remains in the correct zone
    assert len(game_state["zones"]["graveyard"]) == 0
    assert len(game_state["zones"]["deck"]) == 0

def test_drone_of_brutality_red_effect_produces_expected_state_change():
    # Mock state setup
    card = {
        "slug": "drone_of_brutality_red",
        "name": "Drone of Brutality",
        "type": "Generic Action - Attack"
    }
    game_state = {
        "zones": {
            "graveyard": [card],
            "deck": []
        }
    }
    
    # Dispatch the trigger event
    dispatch("ON_LEAVE_PLAY", card, game_state)
    
    # Check if the card is now on the bottom of the deck
    assert len(game_state["zones"]["graveyard"]) == 0
    assert len(game_state["zones"]["deck"]) == 1
    assert game_state["zones"]["deck"][0] == card

# --- drone_of_brutality_yellow ---
def test_drone_of_brutality_yellow_ability_fires_on_correct_trigger():
    # Mock state setup
    card = get_card("drone_of_brutality_yellow")
    mock_state = {
        "player": {
            "deck": [],
            "graveyard": [card]
        }
    }
    
    # Dispatch the ON_DEATH trigger
    dispatch(mock_state, "ON_DEATH", card)
    
    # Check if the card is now on the bottom of the deck
    assert mock_state["player"]["deck"] == [card]
    assert mock_state["player"]["graveyard"] == []

def test_drone_of_brutality_yellow_condition_gates_correctly():
    # Mock state setup where card is not in anywhere zone
    card = get_card("drone_of_brutality_yellow")
    mock_state = {
        "player": {
            "deck": [card],
            "graveyard": []
        }
    }
    
    # Dispatch the ON_DEATH trigger
    dispatch(mock_state, "ON_DEATH", card)
    
    # Check if the card remains in the deck and not moved to graveyard
    assert mock_state["player"]["deck"] == [card]
    assert mock_state["player"]["graveyard"] == []

def test_drone_of_brutality_yellow_effect_produces_expected_state_change():
    # Mock state setup where card is in anywhere zone
    card = get_card("drone_of_brutality_yellow")
    mock_state = {
        "player": {
            "deck": [],
            "graveyard": [card]
        }
    }
    
    # Dispatch the ON_DEATH trigger
    dispatch(mock_state, "ON_DEATH", card)
    
    # Check if the card is now on the bottom of the deck
    assert mock_state["player"]["deck"] == [card]
    assert mock_state["player"]["graveyard"] == []

# --- emerging_power_blue ---
def test_emerging_power_blue_go_again():
    card = get_card("emerging_power_blue")
    assert card is not None
    state = {
        "active_player": "player1",
        "phase": "action",
        "hand": [{"slug": "guardian_attack_action"}],
        "discard_pile": [],
        "permanent_area": [card]
    }
    
    # Simulate the start of turn trigger
    dispatch("START_OF_TURN", state)
    
    # Check if the card is destroyed
    assert card not in state["permanent_area"]
    
    # Play a Guardian attack action card
    played_card = state["hand"].pop(0)
    state["played_cards"] = [played_card]
    
    # Simulate the on_play trigger
    dispatch("ON_PLAY", state)
    
    # Check if the attack power is modified
    assert played_card.get("attack_power") == 1

def test_emerging_power_blue_not_active_player():
    card = get_card("emerging_power_blue")
    assert card is not None
    state = {
        "active_player": "player2",
        "phase": "action",
        "hand": [{"slug": "guardian_attack_action"}],
        "discard_pile": [],
        "permanent_area": [card]
    }
    
    # Simulate the start of turn trigger
    dispatch("START_OF_TURN", state)
    
    # Check if the card is not destroyed (wrong player)
    assert card in state["permanent_area"]

def test_emerging_power_blue_not_guardian_attack():
    card = get_card("emerging_power_blue")
    assert card is not None
    state = {
        "active_player": "player1",
        "phase": "action",
        "hand": [{"slug": "non_guardian_action"}],
        "discard_pile": [],
        "permanent_area": [card]
    }
    
    # Simulate the start of turn trigger
    dispatch("START_OF_TURN", state)
    
    # Check if the card is destroyed
    assert card not in state["permanent_area"]
    
    # Play a non-Guardian attack action card
    played_card = state["hand"].pop(0)
    state["played_cards"] = [played_card]
    
    # Simulate the on_play trigger
    dispatch("ON_PLAY", state)
    
    # Check if the attack power is not modified
    assert "attack_power" not in played_card

# --- emerging_power_red ---
def test_emerging_power_red_go_again():
    card = get_card("emerging_power_red")
    state = {
        "active_player": "player1",
        "phase": "action",
        "hand": [{"slug": "emerging_power_red"}],
        "discard_pile": [],
        "play_area": []
    }
    
    # Simulate playing the card
    dispatch("PLAY_CARD", {"card_slug": "emerging_power_red"}, state)
    
    # Check if the card is in play and go_again ability is present
    assert any(card["slug"] == "emerging_power_red" for card in state["play_area"])
    assert any(ability["ability_type"] == "STATIC" and ability["effects"][0]["type"] == "GO_AGAIN" for ability in card["abilities"])

def test_emerging_power_red_destroy_and_modify_attack():
    card = get_card("emerging_power_red")
    state = {
        "active_player": "player1",
        "phase": "action",
        "hand": [{"slug": "emerging_power_red"}, {"slug": "guardian_attack_action"}],
        "discard_pile": [],
        "play_area": []
    }
    
    # Simulate playing the card
    dispatch("PLAY_CARD", {"card_slug": "emerging_power_red"}, state)
    
    # Simulate start of turn trigger
    dispatch("START_OF_TURN", {}, state)
    
    # Check if the card is destroyed
    assert not any(card["slug"] == "emerging_power_red" for card in state["play_area"])
    
    # Play a Guardian attack action card
    dispatch("PLAY_CARD", {"card_slug": "guardian_attack_action"}, state)
    
    # Check if the attack power is modified by +3
    assert any(card["attack_power"] == 3 for card in state["play_area"])

def test_emerging_power_red_no_effect_on_non_guardian():
    card = get_card("emerging_power_red")
    state = {
        "active_player": "player1",
        "phase": "action",
        "hand": [{"slug": "emerging_power_red"}, {"slug": "non_guardian_attack_action"}],
        "discard_pile": [],
        "play_area": []
    }
    
    # Simulate playing the card
    dispatch("PLAY_CARD", {"card_slug": "emerging_power_red"}, state)
    
    # Simulate start of turn trigger
    dispatch("START_OF_TURN", {}, state)
    
    # Check if the card is destroyed
    assert not any(card["slug"] == "emerging_power_red" for card in state["play_area"])
    
    # Play a non-Guardian attack action card
    dispatch("PLAY_CARD", {"card_slug": "non_guardian_attack_action"}, state)
    
    # Check if the attack power is not modified
    assert all(card.get("attack_power", 0) != 3 for card in state["play_area"])

# --- emerging_power_yellow ---
def test_emerging_power_yellow_go_again():
    card = get_card("emerging_power_yellow")
    state = {
        "active_player": "player1",
        "phase": "action",
        "cards_in_play": [card],
        "attacks_played": []
    }
    
    # Simulate the start of turn
    dispatch(state, "START_OF_TURN", card)
    
    # Check if the card is destroyed
    assert card not in state["cards_in_play"]
    
    # Play a Guardian attack action card
    guardian_attack = {
        "type": "attack",
        "class": "Guardian"
    }
    state["attacks_played"].append(guardian_attack)
    
    # Check if the power is modified correctly
    assert guardian_attack.get("power", 0) == 2

def test_emerging_power_yellow_not_active_player():
    card = get_card("emerging_power_yellow")
    state = {
        "active_player": "player1",
        "phase": "action",
        "cards_in_play": [card],
        "attacks_played": []
    }
    
    # Simulate the start of turn for a different player
    dispatch(state, "START_OF_TURN", card)
    
    # Check if the card is not destroyed (condition gate failed)
    assert card in state["cards_in_play"]

def test_emerging_power_yellow_non_guardian_attack():
    card = get_card("emerging_power_yellow")
    state = {
        "active_player": "player1",
        "phase": "action",
        "cards_in_play": [card],
        "attacks_played": []
    }
    
    # Simulate the start of turn
    dispatch(state, "START_OF_TURN", card)
    
    # Play a non-Guardian attack action card
    non_guardian_attack = {
        "type": "attack",
        "class": "NonGuardian"
    }
    state["attacks_played"].append(non_guardian_attack)
    
    # Check if the power is not modified (condition gate failed)
    assert non_guardian_attack.get("power", 0) == 0

# --- enlightened_strike_red ---
def test_enlightened_strike_red_play_cost():
    card = get_card("enlightened_strike_red")
    state = {
        "hand": ["card1", "card2"],
        "deck": []
    }
    new_state = dispatch(card, "PLAY", state)
    assert len(new_state["hand"]) == 1
    assert new_state["hand"][0] == "card1"
    assert len(new_state["deck"]) == 1
    assert new_state["deck"][0] == "card2"

def test_enlightened_strike_red_draw_card():
    card = get_card("enlightened_strike_red")
    state = {
        "hand": [],
        "deck": ["card1", "card2"],
        "flags": {"draw_card": True}
    }
    new_state = dispatch(card, "ON_ATTACK", state)
    assert len(new_state["hand"]) == 1
    assert new_state["hand"][0] == "card1"
    assert len(new_state["deck"]) == 1

def test_enlightened_strike_red_power_bonus():
    card = get_card("enlightened_strike_red")
    state = {
        "attack_power": 5,
        "flags": {"power_bonus": True}
    }
    new_state = dispatch(card, "ON_ATTACK", state)
    assert new_state["attack_power"] == 7

def test_enlightened_strike_red_go_again():
    card = get_card("enlightened_strike_red")
    state = {
        "flags": {"go_again": True}
    }
    new_state = dispatch(card, "ON_ATTACK", state)
    assert new_state.get("go_again") is None

# --- flic_flak_blue ---
def test_flic_flak_blue_ability_fires_on_correct_trigger():
    card = get_card("flic_flak_blue")
    state = {
        "next_defense_card": {"combo": True},
        "defense_value": 5
    }
    new_state = dispatch(state, card)
    assert new_state["defense_value"] == 7

def test_flic_flak_blue_condition_gates_correctly():
    card = get_card("flic_flak_blue")
    state = {
        "next_defense_card": {"combo": False},
        "defense_value": 5
    }
    new_state = dispatch(state, card)
    assert new_state["defense_value"] == 5

def test_flic_flak_blue_effect_produces_expected_state_change():
    card = get_card("flic_flak_blue")
    state = {
        "next_defense_card": {"combo": True},
        "defense_value": 3
    }
    new_state = dispatch(state, card)
    assert new_state["defense_value"] == 5

# --- flic_flak_red ---
def test_flic_flak_red_ability_fires_on_correct_trigger():
    card = get_card("flic_flak_red")
    state = {
        "player": {
            "hand": [],
            "defense_power": 10
        },
        "opponent": {
            "deck": []
        }
    }
    
    # Simulate a defense reaction trigger with a combo card
    event = {
        "type": "DEFENSE_REACTION",
        "card": {
            "slug": "combo_card"
        }
    }
    
    new_state = dispatch(card, state, event)
    assert new_state["player"]["defense_power"] == 12

def test_flic_flak_red_condition_gates_correctly():
    card = get_card("flic_flak_red")
    state = {
        "player": {
            "hand": [],
            "defense_power": 10
        },
        "opponent": {
            "deck": []
        }
    }
    
    # Simulate a defense reaction trigger with a non-combo card
    event = {
        "type": "DEFENSE_REACTION",
        "card": {
            "slug": "non_combo_card"
        }
    }
    
    new_state = dispatch(card, state, event)
    assert new_state["player"]["defense_power"] == 10

def test_flic_flak_red_effect_produces_expected_state_change():
    card = get_card("flic_flak_red")
    state = {
        "player": {
            "hand": [],
            "defense_power": 8
        },
        "opponent": {
            "deck": []
        }
    }
    
    # Simulate a defense reaction trigger with a combo card
    event = {
        "type": "DEFENSE_REACTION",
        "card": {
            "slug": "combo_card"
        }
    }
    
    new_state = dispatch(card, state, event)
    assert new_state["player"]["defense_power"] == 10

# --- flic_flak_yellow ---
def test_flic_flak_yellow_ability_fires_on_correct_trigger():
    card = get_card("flic_flak_yellow")
    state = {
        "player": {
            "hand": [],
            "defense": 0
        },
        "opponent": {
            "deck": []
        }
    }
    trigger_event = {
        "type": "DEFENSE_REACTION",
        "card": {
            "slug": "combo_card",
            "abilities": [
                {
                    "ability_type": "COMBO"
                }
            ]
        }
    }
    dispatch(card, state, trigger_event)
    assert state["player"]["defense"] == 2

def test_flic_flak_yellow_condition_gates_correctly():
    card = get_card("flic_flak_yellow")
    state = {
        "player": {
            "hand": [],
            "defense": 0
        },
        "opponent": {
            "deck": []
        }
    }
    trigger_event = {
        "type": "DEFENSE_REACTION",
        "card": {
            "slug": "non_combo_card",
            "abilities": []
        }
    }
    dispatch(card, state, trigger_event)
    assert state["player"]["defense"] == 0

def test_flic_flak_yellow_effect_produces_expected_state_change():
    card = get_card("flic_flak_yellow")
    state = {
        "player": {
            "hand": [],
            "defense": 5
        },
        "opponent": {
            "deck": []
        }
    }
    trigger_event = {
        "type": "DEFENSE_REACTION",
        "card": {
            "slug": "combo_card",
            "abilities": [
                {
                    "ability_type": "COMBO"
                }
            ]
        }
    }
    dispatch(card, state, trigger_event)
    assert state["player"]["defense"] == 7
