"""Weapon attacks in the live action path + Graphene Chelicera + orb_weaver.

Weapon attacks were previously only generated by the dead actions.legal_actions
path; play.available_actions now offers them (_add_weapon_attacks). Covers:
  * a real weapon (Anothos-style) is offered and launches combat
  * per-turn / exhaustion gating and start-of-turn reset
  * the Graphene Chelicera token is attackable (fields inherited from the DB)
  * orb_weaver's COST_MODIFIER makes Graphene attacks cost {r} less
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from engine.actions import Action, ActionType
from engine.card import Card, CardDB
from engine.card_effects.dsl import load_all_cards
from engine.engine import start_of_turn_refresh_player
from engine.play import available_actions, _calculate_resource_cost
from engine.state import GameState, Player, Step

load_all_cards()

_DB = CardDB()


def _hero(pid, slug="test_hero"):
    c = Card(slug=slug, name=slug, types=["Hero"], base_life=40, base_intellect=4)
    c.owner = pid
    c.controller = pid
    return c


def _state(p1_hero="test_hero"):
    st = GameState(
        players={1: Player(1, _hero(1, p1_hero)), 2: Player(2, _hero(2))},
        active_player=1,
        player_agents={1: lambda s, o, context=None: (o[0] if o else None),
                       2: lambda s, o, context=None: (o[0] if o else None)},
        step=Step.ACTION, turn_number=1, combat=None, done=False, winner=None,
    )
    st.card_db = _DB
    st.players[1].action_points = 1
    st.players[1].resources = 5
    return st


def _equip_weapon(st, slug, pid=1):
    wc = _DB.get(slug)
    wc.owner = pid
    wc.controller = pid
    st.players[pid].weapon1.add(wc)
    return wc


def _weapon_attack_actions(st, pid=1):
    return [a for a in available_actions(st, pid)
            if a.type == ActionType.ACTIVATE_CARD and getattr(a, 'is_attack_proxy', False)]


# ── weapon attacks are offered in the live path ──────────────────────────────

def test_weapon_attack_offered_in_action_phase():
    st = _state()
    _equip_weapon(st, "anothos")
    acts = _weapon_attack_actions(st)
    assert len(acts) == 1
    assert acts[0].card.slug == "anothos"


def test_weapon_attack_not_offered_without_action_point():
    st = _state()
    _equip_weapon(st, "anothos")
    st.players[1].action_points = 0
    assert _weapon_attack_actions(st) == []


def test_weapon_attack_not_offered_for_non_active_player():
    st = _state()
    _equip_weapon(st, "anothos", pid=2)
    st.players[2].action_points = 1
    st.players[2].resources = 5
    assert _weapon_attack_actions(st, pid=2) == []


def test_weapon_attack_not_offered_when_unaffordable():
    st = _state()
    _equip_weapon(st, "anothos")  # costs 3
    st.players[1].resources = 0
    st.players[1].hand.cards.clear()  # nothing to pitch either
    assert _weapon_attack_actions(st) == []


def test_weapon_attack_gated_after_attacking():
    from engine.play import apply_action
    st = _state()
    _equip_weapon(st, "anothos")
    act = _weapon_attack_actions(st)[0]
    apply_action(st, act)
    # The attack is on the stack as an activated attack layer.
    assert any(e.is_attack for e in st.stack_entries)
    # Weapon used this turn → no further weapon attacks offered.
    st.stack_entries.clear()  # simulate combat consuming the entry
    st.players[1].action_points = 1
    assert _weapon_attack_actions(st) == []
    # Start of next turn: weapon readies again.
    start_of_turn_refresh_player(st, 1)
    st.players[1].action_points = 1
    st.players[1].resources = 5
    assert len(_weapon_attack_actions(st)) == 1


# ── Graphene Chelicera token attacks ─────────────────────────────────────────

def _graphene_equipped_state(hero="arakni_orb_weaver"):
    from engine.effect_keywords import create_token
    st = _state(p1_hero=hero)
    create_token(st, target_player_id=1, token_slug="graphene_chelicera",
                 destination="weapon_slot")
    return st


def test_graphene_token_attack_is_offered():
    st = _graphene_equipped_state(hero="test_hero")
    acts = _weapon_attack_actions(st)
    assert len(acts) == 1
    assert acts[0].card.slug == "graphene_chelicera"


def test_graphene_token_attack_launches_stack_attack():
    from engine.play import apply_action
    st = _graphene_equipped_state(hero="test_hero")
    act = _weapon_attack_actions(st)[0]
    apply_action(st, act)
    assert any(e.is_attack for e in st.stack_entries)


def test_graphene_costs_one_normally():
    st = _graphene_equipped_state(hero="test_hero")
    act = _weapon_attack_actions(st)[0]
    assert _calculate_resource_cost(st, act) == 1


def test_orb_weaver_reduces_graphene_cost_to_zero():
    st = _graphene_equipped_state(hero="arakni_orb_weaver")
    act = _weapon_attack_actions(st)[0]
    assert _calculate_resource_cost(st, act) == 0


def test_orb_weaver_does_not_reduce_other_weapons():
    st = _state(p1_hero="arakni_orb_weaver")
    _equip_weapon(st, "anothos")
    act = _weapon_attack_actions(st)[0]
    assert _calculate_resource_cost(st, act) == 3  # unmodified
