"""Card effect coverage gap analysis for subtask-1-2.

Parses slug_index.json (4,561 cards) and cross-references against:
  - CARD_TRIGGERS in triggers.py (custom card-specific triggers)
  - build_keyword_triggers() in triggers.py (keyword auto-handling)
  - DB seed_data.sql (serialized card triggers)
Produces a complete gap analysis with exact counts.
"""
import json
import re
import os

SLUG_PATH = r"C:\Users\Joseph\Desktop\FAB_Sim\card_data\slug_index.json"
REPORT_PATH = "docs/reports/card_coverage_gap_analysis.md"


def main():
    with open(SLUG_PATH, encoding="utf-8") as f:
        data = json.load(f)
    by_slug = data["by_slug"]
    total = len(by_slug)

    # --- 1. CARD_TRIGGERS from triggers.py ---
    with open("engine/card_effects/triggers.py", encoding="utf-8") as f:
        trig_content = f.read()
    card_trigger_slugs = set(re.findall(r'CARD_TRIGGERS\["([a-z0-9_]+)"\]', trig_content))

    # --- 2. DB seed_data slugs ---
    with open("engine/card_effects/db/seed_data.sql", encoding="utf-8") as f:
        seed = f.read()
    db_slugs = set(re.findall(r"INSERT INTO card_triggers.*?VALUES \('([^']+)'", seed))

    custom_slugs = card_trigger_slugs | db_slugs

    # --- 3. Keyword handling ---
    handled_keywords = set()
    passthrough_keywords = set()

    # Extract build_keyword_triggers function body
    bkt_match = re.search(
        r'def build_keyword_triggers\(.*?\).*?:\n(.*?)(?=\ndef |\Z)',
        trig_content, re.DOTALL
    )
    if bkt_match:
        bkt_body = bkt_match.group(1)
        # Find triggering keywords (kw_base == "xxx")
        for m in re.finditer(r'kw_base\s*==\s*"([^"]+)"', bkt_body):
            handled_keywords.add(m.group(1))
        # Find endswith patterns
        for m in re.finditer(r'kw_base\.endswith\("([^"]+)"\)', bkt_body):
            handled_keywords.add(m.group(1))
        # Find passthrough keywords in `kw_base in (...)` — may span multiple lines
        for m in re.finditer(r'kw_base\s+in\s+\(([^)]+)\)', bkt_body):
            for kw in re.findall(r'"([^"]+)"', m.group(1)):
                passthrough_keywords.add(kw)

    all_handled_kw = handled_keywords | passthrough_keywords

    # Cards with at least one triggering keyword
    keyword_triggered_cards = set()
    # Cards with keywords that are recognized (triggering or passthrough)
    keyword_recognized_cards = set()
    for s, card in by_slug.items():
        kws = card.get("card_keywords") or []
        for kw in kws:
            kw_base = re.sub(r"\s+\d+$", "", kw.strip()).lower()
            if kw_base in handled_keywords or (kw_base.endswith("fusion") and "fusion" in handled_keywords):
                keyword_triggered_cards.add(s)
            if kw_base in all_handled_kw:
                keyword_recognized_cards.add(s)

    # --- Classify all cards ---
    # "Vanilla" = no functional text beyond keyword names, or truly empty
    # "Needs custom" = has functional text describing unique effects
    vanilla_cards = set()
    cards_needing_effects = set()

    for s, card in by_slug.items():
        ft = (card.get("functional_text_plain") or "").strip()
        kws = card.get("card_keywords") or []

        if not ft:
            vanilla_cards.add(s)
            continue

        # Strip keyword names from functional text to see if there's remaining effect text
        remaining = ft
        for kw in kws:
            remaining = remaining.replace(kw, "")
        # Strip common non-effect text patterns
        remaining = re.sub(r"(Legendary|Unlimited|Universal)", "", remaining)
        remaining = remaining.strip(" \n\t,.-;:()")

        if not remaining:
            vanilla_cards.add(s)
        else:
            cards_needing_effects.add(s)

    # --- Coverage categories ---
    covered_by_custom = custom_slugs & set(by_slug.keys())
    covered_by_keyword = keyword_triggered_cards - covered_by_custom
    truly_vanilla = vanilla_cards - covered_by_custom - keyword_triggered_cards

    uncovered = cards_needing_effects - covered_by_custom - keyword_triggered_cards

    # --- Generate report ---
    lines = []
    lines.append("# Card Effect Coverage Gap Analysis")
    lines.append("")
    lines.append(f"**Generated by**: `scripts/gap_analysis.py`")
    lines.append(f"**Total cards in slug_index.json**: {total}")
    lines.append("")
    lines.append("## Source Counts")
    lines.append("")
    lines.append(f"| Source | Count |")
    lines.append(f"|--------|-------|")
    lines.append(f"| CARD_TRIGGERS in triggers.py | {len(card_trigger_slugs)} |")
    lines.append(f"| DB seed_data.sql slugs | {len(db_slugs)} |")
    lines.append(f"| Overlap (triggers.py = seed_data) | {len(card_trigger_slugs & db_slugs)} |")
    lines.append(f"| **Unique custom-effect slugs** | **{len(custom_slugs)}** |")
    lines.append(f"| Keyword bases handled (triggering) | {len(handled_keywords)} |")
    lines.append(f"| Keyword bases handled (passthrough) | {len(passthrough_keywords)} |")
    lines.append(f"| Cards with triggering keywords | {len(keyword_triggered_cards)} |")
    lines.append("")
    lines.append("## Handled Keywords")
    lines.append("")
    lines.append("**Triggering keywords** (auto-registered as TriggerDefs):")
    for kw in sorted(handled_keywords):
        lines.append(f"- `{kw}`")
    lines.append("")
    lines.append("**Passthrough keywords** (recognized but no trigger — static abilities):")
    for kw in sorted(passthrough_keywords):
        lines.append(f"- `{kw}`")
    lines.append("")
    lines.append("## Coverage Summary")
    lines.append("")
    lines.append(f"| Category | Count | % of Total |")
    lines.append(f"|----------|-------|------------|")
    lines.append(f"| Custom triggers (code+DB) | {len(covered_by_custom)} | {len(covered_by_custom)/total*100:.1f}% |")
    lines.append(f"| Keyword-auto-handled (not custom) | {len(covered_by_keyword)} | {len(covered_by_keyword)/total*100:.1f}% |")
    lines.append(f"| Vanilla (no effect text) | {len(truly_vanilla)} | {len(truly_vanilla)/total*100:.1f}% |")
    covered_total = len(covered_by_custom) + len(covered_by_keyword) + len(truly_vanilla)
    lines.append(f"| **Total covered** | **{covered_total}** | **{covered_total/total*100:.1f}%** |")
    lines.append(f"| **UNCOVERED (need implementation)** | **{len(uncovered)}** | **{len(uncovered)/total*100:.1f}%** |")
    lines.append("")

    lines.append("## Uncovered Cards by Type")
    lines.append("")
    type_counts = {}
    for s in uncovered:
        card = by_slug[s]
        types = tuple(card.get("types") or ["Unknown"])
        key = " / ".join(types)
        type_counts[key] = type_counts.get(key, 0) + 1
    lines.append(f"| Card Type | Count |")
    lines.append(f"|-----------|-------|")
    for t, c in sorted(type_counts.items(), key=lambda x: -x[1]):
        lines.append(f"| {t} | {c} |")
    lines.append("")

    # Unhandled keywords analysis
    lines.append("## Unhandled Keywords")
    lines.append("")
    lines.append("Keywords found on cards but NOT handled by build_keyword_triggers:")
    lines.append("")
    unhandled_kw_counts = {}
    for s, card in by_slug.items():
        for kw in (card.get("card_keywords") or []):
            kw_base = re.sub(r"\s+\d+$", "", kw.strip()).lower()
            if kw_base not in all_handled_kw and not (kw_base.endswith("fusion") and "fusion" in handled_keywords):
                unhandled_kw_counts[kw_base] = unhandled_kw_counts.get(kw_base, 0) + 1
    lines.append(f"| Keyword | Card Count |")
    lines.append(f"|---------|------------|")
    for kw, c in sorted(unhandled_kw_counts.items(), key=lambda x: -x[1]):
        lines.append(f"| {kw} | {c} |")
    lines.append("")

    # Custom trigger slugs list
    lines.append("## Implemented Custom Trigger Slugs (118)")
    lines.append("")
    for s in sorted(custom_slugs):
        name = by_slug.get(s, {}).get("name", s)
        lines.append(f"- `{s}` ({name})")
    lines.append("")

    # Full uncovered list
    lines.append(f"## Full Uncovered Card List ({len(uncovered)} cards)")
    lines.append("")
    for s in sorted(uncovered):
        card = by_slug[s]
        name = card.get("name", s)
        ft = (card.get("functional_text_plain") or "")[:80].replace("\n", " ")
        lines.append(f"- `{s}`: {name} — {ft}")

    report = "\n".join(lines)
    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write(report)

    # Print summary
    print("=" * 60)
    print("CARD EFFECT COVERAGE GAP ANALYSIS")
    print("=" * 60)
    print(f"Total cards:                         {total}")
    print(f"Custom triggers (CARD_TRIGGERS):     {len(card_trigger_slugs)}")
    print(f"DB seed_data slugs:                  {len(db_slugs)}")
    print(f"  (100% overlap — seed mirrors code)")
    print(f"Keyword bases with triggers:         {len(handled_keywords)}")
    print(f"Keyword bases passthrough:           {len(passthrough_keywords)}")
    print(f"Cards with triggering keywords:      {len(keyword_triggered_cards)}")
    print()
    print(f"Covered by custom triggers:          {len(covered_by_custom)}")
    print(f"Covered by keyword auto-handling:    {len(covered_by_keyword)}")
    print(f"Vanilla (no effects needed):         {len(truly_vanilla)}")
    print(f"TOTAL COVERED:                       {covered_total} ({covered_total/total*100:.1f}%)")
    print(f"UNCOVERED (need implementation):     {len(uncovered)} ({len(uncovered)/total*100:.1f}%)")
    print()
    print(f"Report written to: {REPORT_PATH}")


if __name__ == "__main__":
    main()
