-- seed_data.sql — AUTO-GENERATED by generate_seed.py
-- DO NOT EDIT BY HAND — run `python -m engine.card_effects.db.generate_seed` to regenerate.
-- Hand-edit only the token_keywords section; all other sections are overwritten on regeneration.


-- Token keywords
INSERT OR REPLACE INTO token_keywords VALUES ('spectral_shield',  'Ward 1');
INSERT OR REPLACE INTO token_keywords VALUES ('spellbane_aegis',  'Spellvoid 1');
INSERT OR REPLACE INTO token_keywords VALUES ('aether_ashwing',   'Arcane Barrier 1');


-- ===========================================================================
-- CARD TRIGGERS (auto-generated from CARD_TRIGGERS dict)
-- ===========================================================================

-- aether_bindings_of_the_third_age
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('aether_bindings_of_the_third_age', 'leaves_arena', 'none', '{}', NULL, 'custom', '{}', '_aether_bindings_sigil_leave', 0, 0);

-- aether_wildfire_red
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('aether_wildfire_red', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_aether_wildfire_on_play', 0, 0);

-- apex_bonebreaker
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('apex_bonebreaker', 'defend', 'custom', '{}', '_apex_defend_condition', 'custom', '{"lambda":"effect_fn=lambda c, e, s: create_token(s, _controller_id(c), \"might\"),"}', NULL, 0, 0);

-- arakni_marionette
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('arakni_marionette', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_arakni_marionette_attack_buff', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('arakni_marionette', 'hit', 'none', '{}', NULL, 'custom', '{}', '_arakni_marionette_hit_go_again', 0, 1);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('arakni_marionette', 'combat_chain_close', 'none', '{}', NULL, 'custom', '{}', '_arakni_marionette_chain_close_cleanup', 0, 2);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('arakni_marionette', 'start_of_end_phase', 'none', '{}', NULL, 'custom', '{}', '_arakni_marionette_end_phase', 0, 3);

-- art_of_desire_body
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('art_of_desire_body', 'hit', 'none', '{}', NULL, 'custom', '{}', '_art_of_desire_body_hit', 0, 0);

-- battering_bolt
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('battering_bolt', 'hit', 'none', '{}', NULL, 'custom', '{}', '_battering_bolt_hit', 0, 0);

-- big_bully
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('big_bully', 'attacking', 'custom', '{}', '_is_this_attacking', 'custom', '{}', '_big_bully_attacking', 0, 0);

-- big_game_trophy_shot
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('big_game_trophy_shot', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_big_game_trophy_on_play', 0, 0);

-- blacktek_whisperers
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('blacktek_whisperers', 'start_of_turn', 'none', '{}', NULL, 'custom', '{}', '_blacktek_whisperers_start_turn', 0, 0);

-- blast_to_oblivion
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('blast_to_oblivion', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_blast_to_oblivion_attack', 0, 0);

-- blink
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('blink', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: effect_gain_action_point(s, _controller_id(c))),"}', NULL, 0, 0);

-- blue_fin_harpoon
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('blue_fin_harpoon', 'hit', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _go_fish_hit(c, e, s,\n                   lambda card: card.pitch == 3)),"}', NULL, 0, 0);

-- booze
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('booze', 'enters_arena', 'none', '{}', NULL, 'custom', '{}', '_booze_enters_arena', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('booze', 'leaves_arena', 'none', '{}', NULL, 'custom', '{}', '_booze_leaves_arena', 0, 1);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('booze', 'start_of_turn', 'none', '{}', NULL, 'custom', '{}', '_booze_start_of_turn', 0, 2);

-- catch_of_the_day
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('catch_of_the_day', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_catch_of_the_day_on_play', 0, 0);

-- chain_of_brutality
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('chain_of_brutality', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_chain_of_brutality_attacking', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('chain_of_brutality', 'hit', 'none', '{}', NULL, 'custom', '{}', '_chain_of_brutality_hit', 0, 1);

-- channel_lightning_valley
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('channel_lightning_valley', 'damage_dealt', 'none', '{}', NULL, 'custom', '{}', '_channel_lightning_damage', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('channel_lightning_valley', 'start_of_end_phase', 'custom', '{"lambda":"condition_fn=lambda c, e, s: c in s.players[_controller_id(c)].auras.cards,"}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: channel_upkeep(c, \"Lightning\", s),"}', NULL, 0, 1);

-- cheating_scoundrel
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('cheating_scoundrel', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_cheating_scoundrel_on_play', 0, 0);

-- cloud_cover
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('cloud_cover', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_cloud_cover_on_play', 0, 0);

-- codex_of_frailty
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('codex_of_frailty', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_codex_of_frailty_on_play', 0, 0);

-- codex_of_inertia
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('codex_of_inertia', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_codex_of_inertia_on_play', 0, 0);

-- comet_storm__shock
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('comet_storm__shock', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_comet_storm_on_play', 0, 0);

-- command_and_conquer
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('command_and_conquer', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_cnc_attacking', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('command_and_conquer', 'hit', 'none', '{}', NULL, 'custom', '{}', '_cnc_on_hit', 0, 1);

-- consign_to_cosmos__shock
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('consign_to_cosmos__shock', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_consign_to_cosmos_on_play', 0, 0);

-- crown_of_dominion
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('crown_of_dominion', 'enters_arena', 'none', '{}', NULL, 'custom', '{}', '_crown_of_dominion_equip', 0, 0);

-- current_funnel
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('current_funnel', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_current_funnel_on_play', 0, 0);

-- cut_from_the_same_cloth_blue
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('cut_from_the_same_cloth_blue', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _cut_from_cloth_on_play(c, e, s, 2)),"}', NULL, 0, 0);

-- cut_from_the_same_cloth_red
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('cut_from_the_same_cloth_red', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _cut_from_cloth_on_play(c, e, s, 4)),"}', NULL, 0, 0);

-- cut_from_the_same_cloth_yellow
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('cut_from_the_same_cloth_yellow', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _cut_from_cloth_on_play(c, e, s, 3)),"}', NULL, 0, 0);

-- death_touch
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('death_touch', 'hit', 'none', '{}', NULL, 'custom', '{}', '_death_touch_hit', 0, 0);

-- electromagnetic_somersault
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('electromagnetic_somersault', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_em_somersault_on_play', 0, 0);

-- electrostatic_discharge
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('electrostatic_discharge', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_electrostatic_on_play', 0, 0);

-- etchings_of_arcana
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('etchings_of_arcana', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_etchings_on_play', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('etchings_of_arcana', 'damage_dealt', 'custom', '{"lambda":"condition_fn=lambda c, e, s: surge_check(e, 4),"}', NULL, 'custom', '{}', '_etchings_surge', 0, 1);

-- flash_of_brilliance
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('flash_of_brilliance', 'defend', 'custom', '{"lambda":"condition_fn=lambda c, e, s: s.combat and c in s.combat.defending_cards,"}', NULL, 'custom', '{}', '_flash_brilliance_defend', 1, 0);

-- flick_knives
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('flick_knives', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_flick_knives_on_play', 0, 0);

-- flittering_charge
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('flittering_charge', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_flittering_charge_on_play', 0, 0);

-- frailty_trap
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('frailty_trap', 'defend', 'custom', '{"lambda":"condition_fn=lambda c, e, s: s.combat and c in s.combat.defending_cards,"}', NULL, 'custom', '{}', '_frailty_trap_defend', 0, 0);

-- fyendals_spring_tunic
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('fyendals_spring_tunic', 'start_of_turn', 'none', '{}', NULL, 'custom', '{}', '_fst_start_of_turn', 1, 0);

-- gold_the_tip
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('gold_the_tip', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_gold_the_tip_on_play', 0, 0);

-- goldbaited_hook
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('goldbaited_hook', 'hit', 'none', '{}', NULL, 'custom', '{}', '_goldbaited_hook_on_hit', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('goldbaited_hook', 'gold_created', 'none', '{}', NULL, 'custom', '{}', '_goldbaited_hook_gold_created', 0, 1);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('goldbaited_hook', 'start_of_end_phase', 'none', '{}', NULL, 'custom', '{}', '_goldbaited_hook_end_phase', 0, 2);

-- golden_tipple
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('golden_tipple', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_golden_tipple_attack', 1, 0);

-- goldfin_harpoon_yellow
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('goldfin_harpoon_yellow', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_arrow_buffs_on_attack', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('goldfin_harpoon_yellow', 'hit', 'none', '{}', NULL, 'custom', '{}', '_arrow_on_hit_gold', 0, 1);

-- gone_in_a_flash
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('gone_in_a_flash', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_gone_in_a_flash_attack', 0, 0);

-- graphene_chelicera
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('graphene_chelicera', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_dagger_buffs_on_attack', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('graphene_chelicera', 'hit', 'none', '{}', NULL, 'custom', '{}', '_dagger_turn_hit_effects', 0, 1);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('graphene_chelicera', 'hit', 'none', '{}', NULL, 'custom', '{}', '_hunters_klaive_hit', 0, 2);

-- hunters_klaive
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('hunters_klaive', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_dagger_buffs_on_attack', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('hunters_klaive', 'hit', 'none', '{}', NULL, 'custom', '{}', '_hunters_klaive_hit', 0, 1);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('hunters_klaive', 'hit', 'none', '{}', NULL, 'custom', '{}', '_dagger_turn_hit_effects', 0, 2);

-- inertia_trap
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('inertia_trap', 'defend', 'custom', '{"lambda":"condition_fn=lambda c, e, s: s.combat and c in s.combat.defending_cards,"}', NULL, 'custom', '{}', '_inertia_trap_defend', 0, 0);

-- infiltrate
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('infiltrate', 'hit', 'none', '{}', NULL, 'custom', '{}', '_infiltrate_hit', 0, 0);

-- insult_to_injury
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('insult_to_injury', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_insult_to_injury_effect', 0, 0);

-- kayo_underhanded_cheat
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('kayo_underhanded_cheat', 'crowd_boos', 'custom', '{"lambda":"condition_fn=lambda c, e, s: hasattr(e, ''data'') and e.data.get(''player_id'') == _controller_id(c),"}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: create_token(s, _controller_id(c), \"vigor\"),"}', NULL, 0, 0);

-- king_kraken_harpoon
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('king_kraken_harpoon', 'hit', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _go_fish_hit(c, e, s,\n                   lambda card: (\"Action\" in (card.types or [])\n                                 and \"Attack\" not in (card.types or [])))),"}', NULL, 0, 0);

-- king_shark_harpoon
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('king_shark_harpoon', 'hit', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _go_fish_hit(c, e, s,\n                   lambda card: \"Attack\" in (card.types or []) and \"Action\" in (card.types or []))),"}', NULL, 0, 0);

-- kiss_of_death
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('kiss_of_death', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_dagger_buffs_on_attack', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('kiss_of_death', 'hit', 'none', '{}', NULL, 'custom', '{}', '_kiss_of_death_hit', 0, 1);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('kiss_of_death', 'hit', 'none', '{}', NULL, 'custom', '{}', '_dagger_turn_hit_effects', 0, 2);

-- lair_of_the_spider
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('lair_of_the_spider', 'defend', 'custom', '{"lambda":"condition_fn=lambda c, e, s: s.combat and c in s.combat.defending_cards,"}', NULL, 'custom', '{}', '_lair_of_spider_defend', 0, 0);

-- leave_no_witnesses
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('leave_no_witnesses', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_leave_no_witnesses_on_play', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('leave_no_witnesses', 'card_banished', 'none', '{}', NULL, 'custom', '{}', '_leave_no_witnesses_contract', 0, 1);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('leave_no_witnesses', 'hit', 'none', '{}', NULL, 'custom', '{}', '_leave_no_witnesses_hit', 0, 2);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('leave_no_witnesses', 'combat_chain_close', 'none', '{}', NULL, 'custom', '{}', '_leave_no_witnesses_chain_close', 0, 3);

-- looking_for_a_scrap
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('looking_for_a_scrap', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_looking_scrap_on_play', 1, 0);

-- mark_of_the_black_widow
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('mark_of_the_black_widow', 'hit', 'none', '{}', NULL, 'custom', '{}', '_mark_black_widow_hit', 0, 0);

-- mask_of_deceit
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('mask_of_deceit', 'defend', 'none', '{}', NULL, 'custom', '{}', '_mask_of_deceit_defend', 0, 0);

-- mind_warp
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('mind_warp', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_mind_warp_on_play', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('mind_warp', 'damage_dealt', 'custom', '{"lambda":"condition_fn=lambda c, e, s: surge_check(e, 3),"}', NULL, 'custom', '{}', '_mind_warp_surge', 0, 1);

-- mocking_blow_blue
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('mocking_blow_blue', 'attacking', 'custom', '{}', '_is_this_attacking', 'custom', '{"lambda":"effect_fn=lambda c, e, s: _mocking_blow_attacking(c, e, s, 2)),"}', NULL, 0, 0);

-- mocking_blow_red
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('mocking_blow_red', 'attacking', 'custom', '{}', '_is_this_attacking', 'custom', '{"lambda":"effect_fn=lambda c, e, s: _mocking_blow_attacking(c, e, s, 4)),"}', NULL, 0, 0);

-- mocking_blow_yellow
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('mocking_blow_yellow', 'attacking', 'custom', '{}', '_is_this_attacking', 'custom', '{"lambda":"effect_fn=lambda c, e, s: _mocking_blow_attacking(c, e, s, 3)),"}', NULL, 0, 0);

-- murderous_rabble
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('murderous_rabble', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_murderous_rabble_attack', 0, 0);

-- nights_embrace
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('nights_embrace', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_nights_embrace_on_play', 0, 0);

-- nimblism_blue
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('nimblism_blue', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: s.players[_controller_id(c)].current_turn_effects.append(\n            \"nimblism_next_attack_plus1\"),"}', NULL, 0, 0);

-- nimby
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('nimby', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_nimby_effect', 1, 0);

-- null__shock
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('null__shock', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_null_shock_on_play', 0, 0);

-- offensive_behavior
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('offensive_behavior', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_offensive_behavior_attack', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('offensive_behavior', 'hit', 'none', '{}', NULL, 'custom', '{}', '_offensive_behavior_hit', 0, 1);

-- orbweaver_spinneret_blue
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('orbweaver_spinneret_blue', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _orb_weaver_on_play(c, e, s, 1)),"}', NULL, 0, 0);

-- orbweaver_spinneret_red
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('orbweaver_spinneret_red', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _orb_weaver_on_play(c, e, s, 3)),"}', NULL, 0, 0);

-- orbweaver_spinneret_yellow
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('orbweaver_spinneret_yellow', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _orb_weaver_on_play(c, e, s, 2)),"}', NULL, 0, 0);

-- oscilio_constella_intelligence
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('oscilio_constella_intelligence', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_oscilio_track_lightning', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('oscilio_constella_intelligence', 'combat_chain_close', 'none', '{}', NULL, 'custom', '{}', '_oscilio_chain_close_cleanup', 0, 1);

-- overcrowded
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('overcrowded', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_overcrowded_attack', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('overcrowded', 'defend', 'custom', '{"lambda":"condition_fn=lambda c, e, s: s.combat and c in s.combat.defending_cards,"}', NULL, 'custom', '{}', '_overcrowded_defend', 0, 1);

-- pain_in_the_backside
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('pain_in_the_backside', 'hit', 'none', '{}', NULL, 'custom', '{}', '_pain_in_backside_hit', 0, 0);

-- pick_up_the_point
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('pick_up_the_point', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_pick_up_the_point_attack', 1, 0);

-- portside_exchange
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('portside_exchange', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_portside_exchange_on_play', 0, 0);

-- pummel
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('pummel', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_pummel_effect', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('pummel', 'hit', 'none', '{}', NULL, 'custom', '{}', '_pummel_hit_check', 0, 1);

-- reckless_arithmetic
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('reckless_arithmetic', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_reckless_arithmetic_effect', 0, 0);

-- red_fin_harpoon
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('red_fin_harpoon', 'hit', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _go_fish_hit(c, e, s,\n                   lambda card: card.pitch == 1)),"}', NULL, 0, 0);

-- riches_of_tropal_dhani
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('riches_of_tropal_dhani', 'card_pitched', 'none', '{}', NULL, 'custom', '{}', '_riches_pitched', 0, 0);

-- savor_bloodshed
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('savor_bloodshed', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_savor_bloodshed_on_play', 0, 0);

-- scar_tissue_blue
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('scar_tissue_blue', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _scar_tissue_on_play(c, e, s, 1)),"}', NULL, 0, 0);

-- scar_tissue_red
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('scar_tissue_red', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _scar_tissue_on_play(c, e, s, 3)),"}', NULL, 0, 0);

-- scar_tissue_yellow
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('scar_tissue_yellow', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _scar_tissue_on_play(c, e, s, 2)),"}', NULL, 0, 0);

-- schism_of_chaos
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('schism_of_chaos', 'card_pitched', 'none', '{}', NULL, 'custom', '{}', '_schism_of_chaos_pitched', 0, 0);

-- scowling_flesh_bag
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('scowling_flesh_bag', 'defend', 'custom', '{"lambda":"condition_fn=lambda c, e, s: s.combat and c in s.combat.defending_cards,"}', NULL, 'custom', '{}', '_scowling_defend', 0, 0);

-- sea_floor_salvage
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('sea_floor_salvage', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_sea_floor_salvage_on_play', 0, 0);

-- shallow_water_shark_harpoon
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('shallow_water_shark_harpoon', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_shallow_water_attack', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('shallow_water_shark_harpoon', 'hit', 'none', '{}', NULL, 'custom', '{}', '_shallow_water_hit', 0, 1);

-- shifting_tides
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('shifting_tides', 'start_of_turn', 'none', '{}', NULL, 'custom', '{}', '_shifting_tides_start_turn', 0, 0);

-- show_of_strength
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('show_of_strength', 'defend', 'custom', '{}', '_is_this_attacking', 'custom', '{}', '_show_of_strength_defend', 0, 0);

-- shred_blue
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('shred_blue', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _shred_on_play(c, e, s, 2)),"}', NULL, 0, 0);

-- shred_red
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('shred_red', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _shred_on_play(c, e, s, 4)),"}', NULL, 0, 0);

-- shred_yellow
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('shred_yellow', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _shred_on_play(c, e, s, 3)),"}', NULL, 0, 0);

-- sift
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('sift', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_sift_on_play', 0, 0);

-- sigil_of_aether
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('sigil_of_aether', 'start_of_action_phase', 'none', '{}', NULL, 'custom', '{}', '_sigil_aether_action_phase', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('sigil_of_aether', 'leaves_arena', 'none', '{}', NULL, 'custom', '{}', '_sigil_aether_leaves', 0, 1);

-- sigil_of_brilliance
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('sigil_of_brilliance', 'start_of_action_phase', 'none', '{}', NULL, 'custom', '{}', '_sigil_brilliance_action_phase', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('sigil_of_brilliance', 'leaves_arena', 'none', '{}', NULL, 'custom', '{}', '_sigil_brilliance_leaves', 0, 1);

-- sigil_of_conductivity
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('sigil_of_conductivity', 'leaves_arena', 'none', '{}', NULL, 'custom', '{}', '_sigil_conductivity_leaves', 0, 0);

-- sigil_of_lightning
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('sigil_of_lightning', 'start_of_action_phase', 'none', '{}', NULL, 'custom', '{}', '_sigil_lightning_action_phase', 0, 0);
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('sigil_of_lightning', 'leaves_arena', 'none', '{}', NULL, 'custom', '{}', '_sigil_lightning_leaves', 0, 1);

-- sigil_of_solace
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('sigil_of_solace', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: effect_gain_life(s, _controller_id(c), 3),"}', NULL, 0, 0);

-- sink_below
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('sink_below', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_sink_below_effect', 0, 0);

-- snarky_prick
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('snarky_prick', 'attacking', 'none', '{}', NULL, 'custom', '{}', '_snarky_prick_effect', 0, 0);

-- spreading_plague
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('spreading_plague', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_spreading_plague_on_play', 0, 0);

-- stains_of_the_redback_blue
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('stains_of_the_redback_blue', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _stains_on_play(c, e, s, 1)),"}', NULL, 0, 0);

-- stains_of_the_redback_red
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('stains_of_the_redback_red', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _stains_on_play(c, e, s, 3)),"}', NULL, 0, 0);

-- stains_of_the_redback_yellow
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('stains_of_the_redback_yellow', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _stains_on_play(c, e, s, 2)),"}', NULL, 0, 0);

-- steal_victory
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('steal_victory', 'defend', 'custom', '{"lambda":"condition_fn=lambda c, e, s: s.combat and c in s.combat.defending_cards,"}', NULL, 'custom', '{}', '_steal_victory_effect', 0, 0);

-- sunken_treasure
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('sunken_treasure', 'defend', 'custom', '{"lambda":"condition_fn=lambda c, e, s: s.combat and c in s.combat.defending_cards,"}', NULL, 'custom', '{}', '_sunken_treasure_defend', 1, 0);

-- swing_big
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('swing_big', 'combat_chain_close', 'none', '{}', NULL, 'custom', '{}', '_swing_big_close', 0, 0);

-- take_up_the_mantle
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('take_up_the_mantle', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_take_up_mantle_on_play', 0, 0);

-- tarantula_toxin
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('tarantula_toxin', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_tarantula_toxin_on_play', 0, 0);

-- temporal_wobble
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('temporal_wobble', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_temporal_wobble_on_play', 0, 0);

-- three_of_a_kind
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('three_of_a_kind', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_three_of_a_kind_on_play', 0, 0);

-- throw_caution_to_the_wind
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('throw_caution_to_the_wind', 'on_play', 'none', '{}', NULL, 'custom', '{}', '_throw_caution_on_play', 0, 0);

-- to_the_point_blue
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('to_the_point_blue', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _to_the_point_on_play(c, e, s, 1, 2)),"}', NULL, 0, 0);

-- to_the_point_red
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('to_the_point_red', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _to_the_point_on_play(c, e, s, 3, 4)),"}', NULL, 0, 0);

-- to_the_point_yellow
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('to_the_point_yellow', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _to_the_point_on_play(c, e, s, 2, 3)),"}', NULL, 0, 0);

-- up_sticks_and_run_blue
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('up_sticks_and_run_blue', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _up_sticks_on_play(c, e, s, 2)),"}', NULL, 0, 0);

-- up_sticks_and_run_red
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('up_sticks_and_run_red', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _up_sticks_on_play(c, e, s, 4)),"}', NULL, 0, 0);

-- up_sticks_and_run_yellow
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('up_sticks_and_run_yellow', 'on_play', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _up_sticks_on_play(c, e, s, 3)),"}', NULL, 0, 0);

-- yellow_fin_harpoon
INSERT INTO card_triggers (slug, event_type, condition_type, condition_params, condition_fn, effect_type, effect_params, effect_fn, is_optional, intra_card_order) VALUES ('yellow_fin_harpoon', 'hit', 'none', '{}', NULL, 'custom', '{"lambda":"effect_fn=lambda c, e, s: _go_fish_hit(c, e, s,\n                   lambda card: card.pitch == 2)),"}', NULL, 0, 0);


-- ===========================================================================
-- EQUIPMENT ACTIVATIONS (auto-generated)
-- ===========================================================================
INSERT OR REPLACE INTO equipment_activations (slug, activation_cost, activation_cost_fn, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('aether_bindings_of_the_third_age', NULL, NULL, 'custom', '{}', NULL, 'custom', '_aether_bindings_effect');
INSERT OR REPLACE INTO equipment_activations (slug, activation_cost, activation_cost_fn, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('blacktek_whisperers', NULL, NULL, 'none', '{}', NULL, 'custom', '_blacktek_whisperers_ar_effect');
INSERT OR REPLACE INTO equipment_activations (slug, activation_cost, activation_cost_fn, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('fyendals_spring_tunic', NULL, NULL, 'custom', '{}', NULL, 'custom', '_fst_spend_energy');
INSERT OR REPLACE INTO equipment_activations (slug, activation_cost, activation_cost_fn, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('goldbaited_hook', NULL, NULL, 'custom', '{}', NULL, 'custom', '_goldbaited_hook_effect');
INSERT OR REPLACE INTO equipment_activations (slug, activation_cost, activation_cost_fn, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('hammerhead_harpoon_cannon', 4, NULL, 'custom', '{}', NULL, 'custom', '_hammerhead_effect');
INSERT OR REPLACE INTO equipment_activations (slug, activation_cost, activation_cost_fn, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('lightning_greaves', 1, NULL, 'custom', '{}', NULL, 'custom', '_lightning_greaves_effect');
INSERT OR REPLACE INTO equipment_activations (slug, activation_cost, activation_cost_fn, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('old_knocker', NULL, NULL, 'custom', '{}', NULL, 'custom', '_old_knocker_effect');
INSERT OR REPLACE INTO equipment_activations (slug, activation_cost, activation_cost_fn, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('quiver_of_abyssal_depths', 3, NULL, 'custom', '{}', NULL, 'custom', '_quiver_effect');
INSERT OR REPLACE INTO equipment_activations (slug, activation_cost, activation_cost_fn, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('scabskin_leathers', NULL, NULL, 'none', '{}', NULL, 'custom', '_scabskin_roll_d6');
INSERT OR REPLACE INTO equipment_activations (slug, activation_cost, activation_cost_fn, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('sealace_sarong', NULL, NULL, 'custom', '{}', NULL, 'custom', '_sealace_effect');
INSERT OR REPLACE INTO equipment_activations (slug, activation_cost, activation_cost_fn, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('skullbone_crosswrap', NULL, NULL, 'custom', '{}', NULL, 'none', NULL);
INSERT OR REPLACE INTO equipment_activations (slug, activation_cost, activation_cost_fn, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('volzar_the_lightning_rod', NULL, '_volzar_activation_cost', 'custom', '{}', NULL, 'custom', '_volzar_effect');


-- ===========================================================================
-- TURN ATTACK EFFECTS (auto-generated from TURN_ATTACK_EFFECTS dict)
-- ===========================================================================
INSERT OR REPLACE INTO turn_attack_effects (flag, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('cheating_scoundrel_next_attack_+3', 'custom', '{}', NULL, 'custom', '_cheating_scoundrel_next_attack_apply');
INSERT OR REPLACE INTO turn_attack_effects (flag, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('electrostatic_next_attack_+3', 'custom', '{}', NULL, 'custom', '_electrostatic_next_attack_apply');
INSERT OR REPLACE INTO turn_attack_effects (flag, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('goldbaited_hook_next_pirate_hit_gold', 'custom', '{}', NULL, 'custom', '_goldbaited_hook_next_pirate_apply');
INSERT OR REPLACE INTO turn_attack_effects (flag, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('hammerhead_next_arrow_+4', 'custom', '{}', NULL, 'custom', '_hammerhead_next_arrow_apply');
INSERT OR REPLACE INTO turn_attack_effects (flag, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('next_attack_6_base_power', 'any', '{}', NULL, 'custom', '_next_attack_6_base_power_apply');
INSERT OR REPLACE INTO turn_attack_effects (flag, condition_type, condition_params, condition_fn, effect_type, effect_fn) VALUES ('nimblism_next_attack_plus1', 'custom', '{}', NULL, 'custom', '_nimblism_next_attack_plus1_apply');
